### ISSUE TITLE
Mention projects dependencies in the development instructions

### ISSUE THREAD

**Issue by mbultmannuos** [project-chip/zap#1003]
As a nodjs noob, I had a very hard time building the project locally. This was mainly because I didn't see the dependencies (libpixman-1-dev libcairo-dev libsdl-pango-dev libjpeg-dev libgif-dev) mentioned on the https://github.com/project-chip/zap/blob/master/docs/development-instructions.md page. Only after some time I came across the FAQ.
My proposal: Either mention the dependencies directly in the development instructions or provide a link to the FAQ.

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/1277
