### ISSUE TITLE
Doing a project upgrade to a newer SDK might result in a zap upgrade script error that blocks the upgrade

### ISSUE THREAD

**Issue by James-Pitt** [project-chip/zap#1010]
Testing the 4-27 Nightly build for a project SDK upgrade resulted in this error message:
`Problem detected, no action performed: Problem detected, no action performed: AC upgrade script produced no yaml file. It may have crashed -- check logs.
upgrade was cancelled before attempting to run any adapter pack upgrade scripts.
`

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/commit/4382b5b5015cb96d2fcce6f18e745b2c5cb01243

This commit has the fix. It should be in the next nightly build.
