### ISSUE TITLE
zap macos arm64 zap-cli binary missing

### ISSUE THREAD

**Issue by mykrupp** [project-chip/zap#1029]
I downloaded the nightly zap run (zap-mac-arm64) from yesterday 5/16. Tried to open zap with ./scripts/tool/zap/run_zaptool.sh  and I get the following errors. I also noticed that zap-mac-arm64 does not have zap-cli included with the package. 

I am on an M1 mac(arm64 chip). After this I tested zap-mac-x64, which actually worked for me and brought up zap.

**Comment by jingteng25742** [comment]
It is expected that zap-mac-arm64 does not have zap-cli atm. The build tool used for CLI building only has experiemntal support atm and not quite working.

**Comment by yesnoyes** [comment]
I am getting error when trying to run this on M1 Mac-

connectedhomeip % ./scripts/tools/zap/run_zaptool.sh
ARGS: 
bash: zap: command not found

Anyone knows how to install and run zap on M1 Mac?

**Comment by jingteng25742** [comment]
Per the latest nightly builds, the [zap-mac-arm64.zip](https://github.com/project-chip/zap/releases/download/v2023.10.24-nightly/zap-mac-arm64.zip)
