### ISSUE TITLE
In the zap UI, some attributes or event state or values do not reflect the zap config

### ISSUE THREAD

**Issue by jmartinez-silabs** [project-chip/zap#1054]
When opening a zap file in the Zap UI, Events are shown as disabled when there are in fact enabled in the zap file

here an example for the all-cluster-app.zap The following access control cluster events are enabled
```
          "events": [
            {
              "name": "AccessControlEntryChanged",
              "code": 0,
              "mfgCode": null,
              "side": "server",
              "included": 1
            },
            {
              "name": "AccessControlExtensionChanged",
              "code": 1,
              "mfgCode": null,
              "side": "server",
              "included": 1
            }
```
But the UI shows them as disabled.
![image](https://github.com/project-chip/zap/assets/67972863/daa39f09-42b3-42f4-adcf-db2ecb2c5cb4)

You can enable them, save the file and close it. Re-open it and the UI will show those events as disabled again. The zap file will not be impacted, the event stay actually enabled and you can generate correctly.

I have seen similar phenomenon with default values set for attributes in the UI. Config files are saved correctly with the correct default values. But if you reopen it in the zap UI the value box will be empty.

**Comment by paulr34** [comment]
fixed in latest commit + nightly
