### ISSUE TITLE
Picking template should be optional

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#1068]
1.) Run `npm run zapall`
2.) See how you land on the "ZCL and templates configuration page".
3.) You are FORCED to choose a "Zap Generation Template", otherwise the SUBMIT button stays disabled.

This is wrong. You should be able to proceed even if you don't pick a generation template. It's a valid session that has zero templates. It just doesn't generate anything. But you can still edit and save the zap file.

**Comment by paulr34** [comment]
this has been fixed
