### ISSUE TITLE
ZAP UI is completely broken for Matter .zap files

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#1080]
Steps to reproduce:

1. Check out ZAP tip, or use ZAP binary from tip.
2. Check out Matter.
3. In the Matter repository, run `./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap`

This gives a completely broken UI; see screenshot in https://github.com/project-chip/connectedhomeip/issues/28102, and the "SUBMIT" button there is disabled.

Git bisect says:
```
11e51dc875a723530f6abfadf9d945a5b3203ea9 is the first bad commit
commit 11e51dc875a723530f6abfadf9d945a5b3203ea9
Author: paulr34 <64710345+paulr34@users.noreply.github.com>
Date:   Tue Jul 18 10:34:54 2023 -0400

    init load (#1055)
```

@paulr34 @tecimovic @brdandu 

This is blocking Matter development.

**Comment by paulr34** [comment]
checking now

**Comment by paulr34** [comment]
There is no geo-template.json in this scenario which is strange. I will reproduce and fix. Thanks.

**Comment by bzbarsky-apple** [comment]
> There is no gen-template.json in this scenario which is strange.

What is gen-template.json?  There are none in Matter....  There are things of type "gen-templates-json" which have other names, though...

(Unrelated, perhaps: `docs/sdk-integration.md` talks about both `gen-template.json` and `gen-templates.json`.... are those the same thing?)

**Comment by mideayanghui** [comment]
@paulr34 Hello Paul, #1080's PR didn't solved this problem  after I pull the master branch to local, do you have some suggestion?

**Comment by paulr34** [comment]
Did you click submit

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paulr34** [comment]
> 
> 
> @paulr34 Hello Paul, #1080's PR didn't solved this problem  after I pull the master branch to local, do you have some suggestion?

Did you click submit? I tested it with the above reproduced and it worked every time. Plus I tested it with other apps.

**Comment by paulr34** [comment]
> > 
> > 
> > @paulr34 Hello Paul, #1080's PR didn't solved this problem  after I pull the master branch to local, do you have some suggestion?
> 
> Did you click submit? I tested it with the above reproducer and it worked every time. Plus I tested it with other apps. 

@mideayanghui

**Comment by mideayanghui** [comment]
The submit button can't be clicked.  I am test with connectedhomeip.

![image](https://github.com/project-chip/zap/assets/106149377/03355d00-3527-407c-b324-f1a9740bde5e)

**Comment by paulr34** [comment]
> @paulr34 The submit button can't be clicked.  I am test with connectedhomeip.
> 
> 
> 
> ![image](https://github.com/project-chip/zap/assets/106149377/03355d00-3527-407c-b324-f1a9740bde5e)
> 
> 

That's strange because I deleted the code which disables that button...

In the morning I'll delete my local repo and try and reproduce what you're doing from scratch. Thank you for the feedback.

**Comment by paulr34** [comment]
@mideayanghui I just tested this by cloning https://github.com/project-chip/zap.git and running npm install then following the above steps and it works fine...

if the submit button is still not clickable then you must not have the latest commit

**Comment by paulr34** [comment]
@mideayanghui maybe you're using a binary, I am currently making a new one with the fix

**Comment by paulr34** [comment]
ZAP UI not completely broken anymore
