### ISSUE TITLE
Not able to launch ZAP GUI with "v2023.07.21"

### ISSUE THREAD

**Issue by erwinpan1** [project-chip/zap#1084]
# Description

After installing [v2023.07.21-nightly](https://github.com/project-chip/zap/releases/tag/v2023.07.21-nightly) on Linux by  `.deb` , running `zap` cannot launch ZAP GUI correctly.

For example,  running the zap below
```
$ /usr/bin/zap --version
Version: 2023.7.20
Feature level: 97
Hash: b57cef1fc261cedcbee418566a3d1e83b2d200d6
Date: 2023-07-20T18:42:00.000Z
Mode: source 

$ /usr/bin/zap examples/chef/devices/rootnode_onofflight_bbs1b7IaOV.zap
```
It leads to the GUI:
![image](https://github.com/project-chip/zap/assets/7869096/b3e0e5e8-2b9e-43f9-9738-b471c6a2b213)

The expected GUI should be: 

![image](https://github.com/project-chip/zap/assets/7869096/6a1adc76-77ea-4327-84a7-0724ca158f9b)

**Comment by erwinpan1** [comment]
Update current status: after running `$ ./scripts/tools/zap/run_zaptool.sh examples/chef/devices/rootnode_onofflight_bbs1b7IaOV.zap` ( instead of running `/usr/bin/zap  ... zap`, the UI seems to be identify matter:
![image](https://github.com/project-chip/zap/assets/7869096/0225583f-0fd2-47dc-96e1-dc0e4f6dcb16)

However, after clicking "SUBMIT", it shows empty ZAP GUI as :
![image](https://github.com/project-chip/zap/assets/7869096/5f8da9e6-47a9-4fae-a3f9-b59cb53cd354)

**Comment by paulr34** [comment]
@erwinpan1 I was able to load that .zap file with the latest commit. Let me try that nightly next.
![Uploading Screenshot 2023-07-25 at 9.48.44 AM.png…]()

**Comment by erwinpan1** [comment]
Hi @paulr34 , I didn't see any nightly release newer than [v2023.07.21-nightly](https://github.com/project-chip/zap/releases/tag/v2023.07.21-nightly) ?

**Comment by erwinpan1** [comment]
Hi @paulr34 ,  thanks for the update [v2023.07.27-nightly](https://github.com/project-chip/zap/releases/tag/v2023.07.27-nightly). It can successfully bypass *SUBMIT* screen. 

On the other hand, I still cannot load the ZAP file by `run_zaptool.sh`.  I guess there might be environment issue at my side. Is there any trick to debug? Thanks.

```
erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0731_zap0728$ zap --version
Version: 2023.7.27
Feature level: 97
Hash: 390ac916dd601f5c51408c769a92a6f24481b100
Date: 2023-07-27T19:56:16.000Z
Mode: source 
$ zap-cli --version
Version: 2023.7.27
Feature level: 97
Hash: 390ac916dd601f5c51408c769a92a6f24481b100
Date: 2023-07-27T19:56:16.000Z
Mode: binary
Executable: zap-cli 
$ rm -rf ~/.zap/

$ ./scripts/tools/zap/run_zaptool.sh examples/chef/devices/rootnode_onofflight_bbs1b7IaOV.zap

```

**Comment by erwinpan1** [comment]
Hi @paulr34 , here's the steps and the only error message when I'm loading ZAP. (Note that I didn't `source script/bootstrap.sh` because the CIPD will download the older 2023.07.21 ZAP release).
```
$ git log -1 | head -3
commit e059202613e91da78884aec4e1041d76da0af9bf
Author: lpbeliveau-silabs <112982107+lpbeliveau-silabs@users.noreply.github.com>
Date:   Mon Jul 31 20:15:06 2023 -0400

$ whereis zap
zap: /usr/bin/zap

$ zap --version
Version: 2023.7.27
Feature level: 97
Hash: 390ac916dd601f5c51408c769a92a6f24481b100
Date: 2023-07-27T19:56:16.000Z
Mode: source 

$ ./scripts/tools/zap/run_zaptool.sh examples/chef/devices/rootnode_onofflight_bbs1b7IaOV.zap
...
{"level":40,"time":1690867229030,"pid":3668220,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"HTTP server exception.","err":{"type":"TypeError","message":"w.setTitleBarOverlay is not a function","stack":"TypeError: w.setTitleBarOverlay is not a function\n    at IpcMainImpl.<anonymous> (/opt/zap/resources/app.asar/dist/src-electron/ui/window.js:110:11)\n    at IpcMainImpl.emit (node:events:513:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81188)\n    at EventEmitter.emit (node:events:513:28)","alert":"⛔"},"msg":"w.setTitleBarOverlay is not a function"}
...
```

Full debug log is attached:  [debug.log](https://github.com/project-chip/zap/files/12224941/debug.log)

**Comment by paulr34** [comment]
@erwinpan1 can you try deleting your .zap folder

**Comment by erwinpan1** [comment]
Yes. Deleting `~/.zap` doesn't work

**Comment by paulr34** [comment]
> Yes. Deleting `~/.zap` doesn't work

Can you show me your env variables?

**Comment by paulr34** [comment]
@erwinpan1 is this Windows?

**Comment by erwinpan1** [comment]
No, this is on Linux.

**Comment by paulr34** [comment]
@erwinpan1 can you manually delete the .zap folder ? The only way I can reproduce this is with a corrupted .zap folder or a corrupted server...

**Comment by erwinpan1** [comment]
Unfortunately the issue still exists after deleting `.zap` manually. Here is the log

```
erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ whereis zap
zap: /usr/bin/zap
erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ zap --version
Version: 2023.8.4
Feature level: 97
Hash: d9df1e59864c47a77e838d7b096e854c4a64ea5b
Date: 2023-08-04T17:38:35.000Z
Mode: source 
erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ rm -rf ~/.zap
erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ 

erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ ./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap
ARGS: -i "/home/erwinpan/matter/erwinpan1/master_0809_zap/examples/all-clusters-app/all-clusters-common/all-clusters-app.zap"
🔧 Using state directory: /home/erwinpan/.zap
{"level":40,"time":1691573100664,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Check type contradiction in XML metadata for ColorControlOptions with type BITMAP8"}
{"level":40,"time":1691573100705,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Check type contradiction in XML metadata for BarrierControlBarrierPosition with type INT8U"}
{"level":40,"time":1691573101176,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"HTTP server exception.","err":{"type":"TypeError","message":"w.setTitleBarOverlay is not a function","stack":"TypeError: w.setTitleBarOverlay is not a function\n    at IpcMainImpl.<anonymous> (/opt/zap/resources/app.asar/dist/src-electron/ui/window.js:110:11)\n    at IpcMainImpl.emit (node:events:513:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81188)\n    at EventEmitter.emit (node:events:513:28)","alert":"⛔"},"msg":"w.setTitleBarOverlay is not a function"}
{"level":50,"time":1691573101176,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":{"alert":"⛔"}}
{"level":30,"time":1691573101182,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Init message received: WebSocket initialized handshake.. Responding."}
{"level":30,"time":1691573101248,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Loading project(/home/erwinpan/matter/erwinpan1/master_0809_zap/examples)"}
{"level":30,"time":1691573101540,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Loaded project(/home/erwinpan/matter/erwinpan1/master_0809_zap/examples) into database. RESP: {\"sessionId\":2}"}
{"level":50,"time":1691573101576,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":{}}

```

**Comment by paulr34** [comment]
> Unfortunately the issue still exists after deleting `.zap` manually. Here is the log
> 
> 
> 
> ```
> 
> erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ whereis zap
> 
> zap: /usr/bin/zap
> 
> erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ zap --version
> 
> Version: 2023.8.4
> 
> Feature level: 97
> 
> Hash: d9df1e59864c47a77e838d7b096e854c4a64ea5b
> 
> Date: 2023-08-04T17:38:35.000Z
> 
> Mode: source 
> 
> erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ rm -rf ~/.zap
> 
> erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ 
> 
> 
> 
> erwinpan@erwinpan-p1g4lin01:~/matter/erwinpan1/master_0809_zap$ ./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap
> 
> ARGS: -i "/home/erwinpan/matter/erwinpan1/master_0809_zap/examples/all-clusters-app/all-clusters-common/all-clusters-app.zap"
> 
> 🔧 Using state directory: /home/erwinpan/.zap
> 
> {"level":40,"time":1691573100664,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Check type contradiction in XML metadata for ColorControlOptions with type BITMAP8"}
> 
> {"level":40,"time":1691573100705,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Check type contradiction in XML metadata for BarrierControlBarrierPosition with type INT8U"}
> 
> {"level":40,"time":1691573101176,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"HTTP server exception.","err":{"type":"TypeError","message":"w.setTitleBarOverlay is not a function","stack":"TypeError: w.setTitleBarOverlay is not a function\n    at IpcMainImpl.<anonymous> (/opt/zap/resources/app.asar/dist/src-electron/ui/window.js:110:11)\n    at IpcMainImpl.emit (node:events:513:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81188)\n    at EventEmitter.emit (node:events:513:28)","alert":"⛔"},"msg":"w.setTitleBarOverlay is not a function"}
> 
> {"level":50,"time":1691573101176,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":{"alert":"⛔"}}
> 
> {"level":30,"time":1691573101182,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Init message received: WebSocket initialized handshake.. Responding."}
> 
> {"level":30,"time":1691573101248,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Loading project(/home/erwinpan/matter/erwinpan1/master_0809_zap/examples)"}
> 
> {"level":30,"time":1691573101540,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":"Loaded project(/home/erwinpan/matter/erwinpan1/master_0809_zap/examples) into database. RESP: {\"sessionId\":2}"}
> 
> {"level":50,"time":1691573101576,"pid":1009656,"hostname":"erwinpan-p1g4lin01","name":"zap","msg":{}}
> 
> 
> 
> ```

Thank you for this log. Sorry I have been preoccupied with other projects and will get back to this.

**Comment by erwinpan1** [comment]
No problem. I'm still able to work with manually load zap file.
Just ping me when you have any update (e.g. adding some verbose error description).  
BTW, I just found that there's an error when loading zap file. I don't know if this is relevant ? 
![image](https://github.com/project-chip/zap/assets/7869096/5874ed8c-ea77-497d-8f3b-3890badcff20)

**Comment by paulr34** [comment]
The ZAP GUI is able to be launched so this needs to be closed. Please open a new bug if there are other issues.
