### ISSUE TITLE
ZAP UI should not allow editing storage setting for things that are forced to be external

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#1086]
ZAP has a way to force attributes to be external via SDK settings, but the UI will still allow changing the storage value... which will then be ignored.

The UI should not allow setting things that don't match reality.

**Comment by paulr34** [comment]
@YanchengZhou 

if the SDK forces "storageOption" to be external then the toggle should be disabled. Let's meet and discuss if you can take this on.

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/1181
