### ISSUE TITLE
ZAP UI should support setting Parent Endpoints and Composition Type for an Endpoint

### ISSUE THREAD

**Issue by mhazley** [project-chip/zap#1093]
As part of the Matter development for the Fall 2023 release, the concept of a "composed" device has been added using a "tree" composition. 

Device composition is managed via the `PartsList` attribute in the `Descriptor` cluster for an Endpoint when an Endpoint has a device type that can be composed of other devices. 

So, for example, if there's an Air Purifier on Endpoint 1, it could have a parts list of `[2, 3]` to indicate that it is composed of an `Air Quality Sensor` on Endpoint 2 and a `Temperature Sensor` on Endpoint 3. 

This would mean that Endpoint 1 would be set as the Parent of Endpoints 2 & 3 so the SDK can build the parts list appropriately.  

Also, in order to build the parts list in the correct format, the SDK also needs to be able to distinguish between `Tree` or `Flat` composition as this is described in the spec as:

> - Tree pattern of endpoints directly below the composed endpoint.
> - Flat list of all descendent endpoints below the composed endpoint.

So, it would be really useful if we could set a Parent and a Composition Type for an Endpoint in the UI, then this can be parsed by the SDK at setup. 

Currently, we've added API's to set this information programmatically in [this PR](https://github.com/project-chip/connectedhomeip/pull/28410).

**Comment by bzbarsky-apple** [comment]
This is somewhat of a blocker for using ZAP as a "configure and just use the config" thing for the Fall 2023 devices.  The APIs we are adding will let people work around, but at that point they will start asking why they are bothering with the non-programmatic ZAP config at all...

**Comment by bzbarsky-apple** [comment]
Note that Tree vs Flat composition is associated with the device type, so ideally it would just be listed in the XML for the device types and no one would ever set it manually in the UI (but still needs backend support to expose the XML value to allow codegen based on it, perhaps).  What the UI needs is a way to set the parent of an endpoint.

**Comment by paulr34** [comment]
ill set up a meeting with @tbrkollar to discuss the front end changes and ill work on adding the backend support to support the XML

**Comment by jvmahon** [comment]
I'm hoping for a clarification on a related point.  

The matter spec states: 
![image](https://github.com/project-chip/zap/assets/15061942/835efb4c-3d27-4de4-a1a9-87fb67e499fc)

However, when I look at the Zap files for the examples (e.g., the examples in Chef/devices), the "PartsList" is always blank.   

-  Do I not understand what the matter spec requires, or are all the examples non-conforming?  I.e., shouldn't all the examples have their "PartsList" set?

If it should be set, I'm confused as to how.  The Zap entry box for PartsList seems to allow only a single integer digit. However, for a device with multiple endpoints, e.g., https://github.com/project-chip/connectedhomeip/blob/master/examples/chef/devices/rootnode_airpurifier_airqualitysensor_temperaturesensor_humiditysensor_thermostat_56de3d5f45.zap, as I understand it, the PartsList should identify endpoints 1, 2, 3, 4

Any help / clarification / examples would be appreciated.

**Comment by bzbarsky-apple** [comment]
> However, when I look at the Zap files for the examples (e.g., the examples in Chef/devices), the "PartsList" is always blank.

PartsList is computed at runtime from ZAP-provided (or not-ZAP-provided, for that matter) structural data by the SDK, not hardcoded in the ZAP UI.

This would be more clear if https://github.com/project-chip/zap/issues/1145 were fixed, since PartsList would then very clearly not have a way to set its value.

**Comment by jvmahon** [comment]
> This would be more clear if #1145 were fixed, since PartsList would then very clearly not have a way to set its value.

That would be fantastic. As someone new to this, it would certainly be clearer if the ZAP interface didn't suggest you should (or could) complete something where it doesn't make sense.  In those cases a brief "set in software" message (or something along those lines) would help.

**Comment by paulr34** [comment]
done 

Parent Endpoint Feature - https://github.com/project-chip/zap/pull/1257

Matter SDK Helper - https://github.com/project-chip/zap/pull/1259

Disable defaultValue for all Attributes with External Storage -https://github.com/project-chip/zap/pull/1249

**Comment by bzbarsky-apple** [comment]
This does not work right.  Specific problems with the code that was checked in:

1. It's not letting me select the right endpoints as parents.  For example, for all-clusters-app, which has endpoints 0, 1, 2, 65534, it lets me select only 1, 2, 3, 4 as parent endpoint ids.
2. The output from the helper is a mix of integers and NULL, which is not workable.  What it _should_ be is just an array of parent endpoint ids.  Anything without an explicit parent set should have 0 as parent.

**Comment by paulr34** [comment]
thanks @bzbarsky-apple here are PR's to address your concerns 

editing previously made endpoint - https://github.com/project-chip/zap/pull/1263/files

Matter SDK helper (Integer Array) - https://github.com/project-chip/zap/pull/1262

**Comment by paulr34** [comment]
@mhazley hey, the ZAP UI can now support setting a parent endpoint of an endpoint

@mhazley please lmk if you have anymore problems and concerns assuming a second ticket for endpoint composition
