### ISSUE TITLE
[BUG] opening and saving a file in the zap GUI causes OnOff cluster OnOff attribute to be set as non-reportable

### ISSUE THREAD

**Issue by cecille** [project-chip/zap#1106]
see https://github.com/project-chip/connectedhomeip/pull/28647/files#diff-051d0b2abf5d8231836865f71f18789afe10cede6c258ce69ef7d852f03e18b5

**Comment by paulr34** [comment]
will work on this tomorrow

**Comment by paulr34** [comment]
@cecille I created an endpoint with the on/off cluster enabled. By default, the on/off attribute is reportable. Then I saved it and reopened it and it was still reportable. 

Could you provide more details?

**Comment by paulr34** [comment]
maybe you're using an old version of ZAP?

**Comment by paulr34** [comment]
this issue is fixed, if you disagree please reopen!
