### ISSUE TITLE
ZAP on Apple Silicon

### ISSUE THREAD

**Issue by tpitman** [project-chip/zap#1113]
Does zap run on apple silicon macos?

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/1115
yes, just download the Mac .zip file located here

**Comment by tpitman** [comment]
Thank you. I finally found the correct Mac file to download. It was a little confusing trying to figure out what I wanted when I went to the releases page. It might be night to have a separate page just for the releases that contain the installable bits.

The nightly releases seem to be source that you have to build and after an hour of trying I was not able to get that to build on my mac despite updating Node, NPM and Python.

I kept getting the gpy error that others have posted about. No idea how to solve it, but for now having the installable bits works.
