### ISSUE TITLE
Match Studio / UC component integration popup box color with ZAP theme colors

### ISSUE THREAD

**Issue by jingteng25742** [project-chip/zap#1118]
![Screenshot 2023-08-30 at 3 57 19 PM](https://github.com/project-chip/zap/assets/61332088/04d5ef74-bd3e-43c4-9837-05e0b1a8ec1c)

When ZAP is embedded in Studio, a Notify box shows up. The color is a static screen currently and should be updated to match the changing themes of Zigbee / Matter.

The code for the above Notify box is here:
https://github.com/project-chip/zap/blob/master/src/components/ZclCustomZclView.vue#L195

There are 2 states to the box: successful vs failure

![Screenshot 2023-08-31 at 2 06 38 PM](https://github.com/project-chip/zap/assets/61332088/ec2608ab-e925-4bae-9134-f0088a8d9598)
I found another integration relic. 
Please update this window as well.
There is only 1 state, which is mostly displaying of info as FYI

**Comment by tbrkollar** [comment]
i totally agree with you. i will modify it

**Comment by paulr34** [comment]
@jingteng25742 Zigbee is red and a failure is also red..what do you think we should do?

**Comment by jingteng25742** [comment]
Had discuss with @paulr34 / @tbrkollar on Slack. updated ticket with more information. @tbrkollar will brainstorm / work on the ticket more

**Comment by tbrkollar** [comment]
![matter-main-noti-black](https://github.com/project-chip/zap/assets/116916192/0935216e-1df6-4613-b405-fb7364c2f2dd)
![matter-main-noti](https://github.com/project-chip/zap/assets/116916192/43e5308f-7b68-4e7b-9905-c13f5a5ed643)
