### ISSUE TITLE
[BUG] config-data.yaml uses different formats for cluster names

### ISSUE THREAD

**Issue by rochaferraz** [project-chip/zap#1134]
`connectedhome/src/app/common/templates/config-data.yaml` has a few top-level tags. 

The format used by `CommandHandlerInterfaceOnlyClusters`, `DefineBitmaps`, `WeakEnums` seems to be the cluster name with no spaces, converted to CamelCase.

The format used by `ClustersWithInitFunctions`, `ClustersWithAttributeChangedFunctions`, `ClustersWithShutdownFunctions`, and `ClustersWithPreAttributeChangeFunctions` is the cluster name _with_ spaces and no case conversion: as defined in the cluster XML file.

It's a quite confusing, and formats should converge

Context: https://github.com/project-chip/connectedhomeip/pull/29162

**Comment by bzbarsky-apple** [comment]
Note a ZAP issue.  On the ZAP side, this is just doing "look up a string you provide in the list you name".  The strings and list names are all provided in Matter templates.

**Comment by rochaferraz** [comment]
While `CommandHandlerInterfaceOnlyClusters` is indeed processed by the templates `connectedhome/src/app/zap-templates/templates/app/im-cluster-command-handler.zapt` and `connectedhome/src/app/zap-templates/templates/app/callback.zapt`, `ClustersWithInitFunctions` and others are populated by `zap/src-electron/generator/matter/app/zap-templates/templates/app/helper.js`, thus the ticket was opened here.

Happy to open the issue on the matter side of things
