### ISSUE TITLE
External attributes should not have an editable (or any, really) Default field in the UI

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#1145]
For an external attribute the Default field does not make sense.  The value in that field is not used for anything.

Right now, the field exists, and the user can edit it, but then the value is ignored.  This is very misleading and leads to people wasting time setting these values that then get ignored.

I think the UI that would make the most sense is to completely hide the Default field if storage is set to External.  That would avoid showing any currently-set value in it (because that value means nothing), and would avoid users editing the field at all.

Second-best might be just making the field un-editable.

There might be better UI ideas here too, but the important thing is that it should be clear to users that there is no concept of "default value" for external attributes.

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/1181
