### ISSUE TITLE
npm run error

### ISSUE THREAD

**Issue by wissn84** [project-chip/zap#115]
Hi, This is Jeonghwan Kim.
I tried to install ZAP refer to FAQ then succeed to install ZAP on my ubuntu machine.

after run zap,  I meet the below issue? 
Would you help me?

` ✘ ⚙   ~/work/zap   master ±  npm run zap

> zap@0.99.4 zap
> node src-script/zap-start.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json

🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: 742ebb79fbaec6b897be1105859de93fe584bd68 from Tue Mar 02 2021 22:10:54 GMT+0900 (대한민국 표준시)
🔍 Current hash: jJRPde7u50RsCrLfJaRztyBEFmk=
🔍 Previous hash: jJRPde7u50RsCrLfJaRztyBEFmk=
👍 There were no changes to front-end code, so we don't have to rebuild the SPA.
🚀 Executing: electron src-electron/main-process/electron-main.dev.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json
⇝ (node:21240) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
The futex facility returned an unexpected error code.😎 All done: 1s, 462ms.`

**Comment by tecimovic** [comment]
Hey! Is this still a problem?

**Comment by tecimovic** [comment]
I'm closing this issue. I assume it's because DISPLAY was not set.
You can run via `node` or via `xvfb-run` if you're touching electron libraries and you don't have a display.
