### ISSUE TITLE
Command warnings not showing up in ZAP

### ISSUE THREAD

**Issue by brdandu** [project-chip/zap#1174]
The UI warnings are not showing up in ZAP commands. See attached
<img width="456" alt="Screen Shot 2023-10-19 at 11 09 47 AM" src="https://github.com/project-chip/zap/assets/17618965/1e4d157e-97f2-48db-9d78-ac591ca87199">

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/1206

**Comment by paulr34** [comment]
fixed

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/1206
