### ISSUE TITLE
The zap tool does not work on Windows

### ISSUE THREAD

**Issue by KEEPHEADU** [project-chip/zap#1175]
![屏幕截图 2023-10-20 162828](https://github.com/project-chip/zap/assets/115463286/823ba37f-1ccf-4fc7-8c4a-6d1a621b0766)
When I downloaded the Windows version of zap and unzipped it and ran it, the zap tool did not generate .cpp files and .h files as it normally does, and there was an error message in the software. Below is a screenshot of the error message.

**Comment by jingteng25742** [comment]
@paulr34 
I am seeing the same notification text on the latest release version of ZAP. 
Why is the notification window displaying this?

**Comment by paulr34** [comment]
Looking

**Comment by paulr34** [comment]
@KEEPHEADU do you have a gen-template.json? Could you select "extensions" then show me your zcl.json and your gen-template.json? 

The error message is actually correct and telling @KEEPHEADU to add a gen template...

@jingteng25742

**Comment by paulr34** [comment]
@KEEPHEADU After debugging, please try this:

download a Zigbee SDK and open a .zap file with a gen-templates.json and a zcl.json file. This will populate the database and further enable you to generate Zigbee code.

Im not sure how you were generating without a gen-templates.json file.

On the other hand, if you were successfully doing this before then you should "open" one of the files that you created which will load into the database the path of the gen-templates.json file that is mentioned in the .zap file..

Basically, ZAP cannot find the gen-templates.json file unless you tell it where it is. This can be accomplished by opening a .zap file that has "gen-templates.json" mentioned and the corresponding path. The act of opening this file will save that path to the database and now ZAP will know where it is so when you open a blank configuration it will find it.

The main points:
-gen-template.json is required to generate Zigbee apps
-ZAP does not search your computer for one
-if you open a .zap file for a Zigbee application with the path of the gen-template then it will save that path and allow you to use it for other apps

**Comment by jingteng25742** [comment]
@paulr34 
I just launched ZAP standalone without specifying zcl/gen-template/etc.
The issue looks to be the built-in zcl/gen-template metadata are not loaded correct.

**Comment by paulr34** [comment]
okay please make a new issue as this one is misleading
