### ISSUE TITLE
Externalized Helpers

### ISSUE THREAD

**Issue by brdandu** [project-chip/zap#1190]
### Discussed in https://github.com/project-chip/zap/discussions/1188

 Externalized helpers: it would be helpful if there is at least SOME ability to write custom helper code on SDK. Find a middle ground between "full safety" and "do whatever you want". 

One of the ways:
- May be we can come up with some form of standard APIs which give a certain set of baseline data from within ZAP's backend database based on the Data Model schema. The data obtained from these standard APIs can be used in externalized helpers to manipulate data using javascript and write extensive helpers. I understand this will have certain limitations but could this be a reasonable middle ground?

**Comment by paulr34** [comment]
completed
