### ISSUE TITLE
Matter Centric ZAP UI

### ISSUE THREAD

**Issue by brdandu** [project-chip/zap#1193]
### Discussed in https://github.com/project-chip/zap/discussions/1188

  - Deal with what "Defaults" mean. Sort this out in ZAP. Name this as "Init value" or "Boot time value"
  - add hover messages to buttons and such. Need to add tool tip messages for each of the UI columns. Users have been confused on what each column means. Vue tour should be extended to train the user through each of the columns as well.
  - zap UI assumes zigbee, not matter. There are things that make no sense to matter (such as "reportable" toggle)

- Notes:
 - zap is using "default" wrong. "Defaults" in the spec are the "default values" that the "receiver" should assume the values are, if they are omitted. They are not "default" values for attributes at startup, as Zap assumes.

**Comment by paulr34** [comment]
Reportable toggle is already disabled

added this PR which addresses https://github.com/project-chip/zap/pull/1181

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/commit/1fc5cc453f931d99cf690bfde78891137bf2d929
