### ISSUE TITLE
Request for stable zap release matching Matter SDK v1.2.0.1 requirement (minimum 2023.10.14)

### ISSUE THREAD

**Issue by MonicaisHer** [project-chip/zap#1209]
Hello, 

the zap has been used by the Matter project. The Matter SDK recently released version 1.2.0.1, and it requires a minimum zap version of [v2023.10.24](https://github.com/project-chip/connectedhomeip/blob/v1.2.0.1/scripts/tools/zap/zap_execution.py#L26). However, the zap repository only has version 2023.10.24-nightly, and the latest stable release available is v2023.09.28. I am wondering if there is a plan to have a zap stable release equal to or greater than 2023.10.14 to match the Matter release. 

Thank you for any help.

**Comment by paulr34** [comment]
@MonicaisHer I will make a new one today, thank you for this bug!
