### ISSUE TITLE
Add ability to open notifications pane along with the endpoint UI

### ISSUE THREAD

**Issue by brdandu** [project-chip/zap#1232]
Right now the user to go to the notifications pane to see the errors. Then press back to be able to see the endpoint view. This gets even worse when you are on a cluster configuration page where you resolve one of the issues mentioned in the notification page. You have to close that cluster config page then go to notifications page and then go back into endpoint view.
Need to improve the user flow and make the notification pane accessible from anywhere so that the user can quickly fix things instead of going to and fro from everywhere.

**Comment by tbrkollar** [comment]
i implemented this 3 months ago. and it was merged.
https://github.com/tbrkollar/zap/tree/feature/notification-panel
