### ISSUE TITLE
"zap convert" and running the ZAP GUI produce different .zap file output

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#1237]
When "zap convert" gets run, it adds this to the ZAP file:
```
  "log": []
```

When the ZAP UI is run, it removes that line.

So using "convert" and the UI keeps editing the file back and forth.  This leads to a _lot_ of noise in Matter PRs.  See https://github.com/project-chip/connectedhomeip/pull/30389/files for a prime example.

**Comment by tecimovic** [comment]
This was addressed in https://github.com/project-chip/zap/pull/1238
