### ISSUE TITLE
About Profile ID 0x0103 in ZAP tool

### ISSUE THREAD

**Issue by chenek** [project-chip/zap#1241]
As we can see Profile ID 0x0103 in ZAP tool, I suppose Profile ID 0x0103 is specific for Matter applications but I cannot find its definition anywhere in Matter specifications. Can anyone confirm this and point to where this profile ID is defined?

**Comment by paulr34** [comment]
In the latest nightly build, profileID has been taken out of the ZAP GUI when creating a Matter app
