### ISSUE TITLE
How to handle "There are multiple of ZCL metadata loaded. Please select the one you wish to use with this configuration."?

### ISSUE THREAD

**Issue by skuangq** [project-chip/zap#1279]
When I am using ZAP tool (ZAP_VERSION=v2023.12.06-nightly) for Matter application, it reports "There are multiple of ZCL metadata loaded. Please select the one you wish to use with this configuration.", and I could not see any endpoints/clusters by choosing any one of the options. 
![ZAP_Err_01](https://github.com/project-chip/zap/assets/127491045/ff40c0e0-af2b-4061-bea3-a1de08ad702e)
![ZAP_Err_02](https://github.com/project-chip/zap/assets/127491045/c255ff38-274b-42bc-8f30-e9c7612f91b7)
![ZAP_Err_03](https://github.com/project-chip/zap/assets/127491045/7f4be181-5776-4bb2-97e3-5d21a525e4fd)

Can someone help me on how to fix this issue? thanks.

**Comment by skuangq** [comment]
It happed when I opening a previously created .zap file.
Seems it related to "/home/user/.zap/zap.sqlite", is there any document can be referenced to understand that file?

**Comment by paulr34** [comment]
@skuangq I am not sure how you ended up here. 

Could you provide steps to reproduce?

A short term solution would be to delete the .zap folder, close ZAP, and reopen ZAP

**Comment by paulr34** [comment]
thank you
