### ISSUE TITLE
ZAP needs to track endpoint composition types

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#1341]
Right now, all ZAP-defined endpoints default to flat composition in the Matter SDK.

This is not right; it should depend on the device types involved.

This means:

1. Flagging device types with this information in the XML.
2. Storing this information in the ZAP database.
3. Making it possible to assign composition types to endpoints during endpoint_config generation.

Right now the Matter SDK has a `SetTreeCompositionForEndpoint` function that all implementors of, say, the refrigerator device type have to remember to call; this is obviously not great.

**Comment by paulr34** [comment]
PR:  https://github.com/project-chip/zap/pull/1364/files

**Comment by paulr34** [comment]
PR for CHIP repo: https://github.com/project-chip/connectedhomeip/pull/34818
