### ISSUE TITLE
profile id is in the endpoint card for Matter

### ISSUE THREAD

**Issue by paulr34** [project-chip/zap#1358]
<img width="284" alt="Screenshot 2024-07-12 at 3 13 02 PM" src="https://github.com/user-attachments/assets/86d1d6b6-e4b2-4dd6-8001-d4aef397576e">
profile id is still present in the endpoint card

**Comment by tbrkollar** [comment]
i have already implemented it. it is in my https://github.com/project-chip/zap/pull/1354

**Comment by tbrkollar** [comment]
it is the same to https://github.com/project-chip/zap/issues/394 issue.

**Comment by paulr34** [comment]
cool thank you!
