### ISSUE TITLE
ZAP Tool generates not compiling Basic Cluster when enabling all Attributes

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/zap#138]
I have enabled all attributes from the Basic Cluster, because they are required by the TE2 test spec. 

<img width="2088" alt="Screen Shot 2021-04-23 at 09 29 25" src="https://user-images.githubusercontent.com/80681009/115835689-d84b9580-a416-11eb-9675-3185a04bf439.png">

This is the resulting zap file:  [config.zap.txt](https://github.com/project-chip/zap/files/6363547/config.zap.txt)

When compiling I get the following error:
```
../src/gen/endpoint_config.h:271:29: error: exponent has no digits
  271 | #define ATTRIBUTE_MAX_SIZE (273ERROR : PartNumber, invalid size, char_stringERROR : ProductURL, invalid size, char_string643212)
      | 
```

And in endpoint_config.h.

```
// Total size of singleton attributes
#define ATTRIBUTE_SINGLETONS_SIZE                                                                                                  \
    (270ERROR : PartNumber, invalid size, char_stringERROR : ProductURL, invalid size, char_string64321)

// Total size of attribute storage
#define ATTRIBUTE_MAX_SIZE (273ERROR : PartNumber, invalid size, char_stringERROR : ProductURL, invalid size, char_string643212)
```

**Comment by paulr34** [comment]
@eve-cxrp I tried reproducing this with all of the attributes enabled but the app built fine. Could you provide more details on how I can reproduce?

**Comment by eve-cxrp** [comment]
Haha, well I guess this issue is deprecated... Since it was reported eons ago 😉.
