### ISSUE TITLE
Matter Device Type Features page

### ISSUE THREAD

**Issue by paulr34** [project-chip/zap#1380]
**A New Features Page**

**Requirements:**

**Phase 1:**

- Create a new page for displaying features per Device Type.
- Update Matter XML to include relevant feature data
- Design the ZAP SQL database accordingly.
- Translate conformance from the Matter spec to the ZAP SQL database and then to the Vue front end.

**Description:**

When creating Matter device types in ZAP, we propose adding a new page called "Features." This page will display all the features listed in the Element Requirements section of the Device Type Matter spec. It will also include data from the Element Requirements section, such as Conformance. This data must be extracted from the Matter data model XML, translated, stored in the ZAP SQL database, and retrieved by the front end via a REST API.

**Use Case:**

As a ZAP user creating a Matter application, I want to select a device type and activate features. By selecting "Features," I should see all possible features supported by the Device Type. This will provide a convenient reference for setting the featureMap attribute bit when finalizing my application.

**Requirements:**

**Phase 2:**

- Implement the ability to toggle optional features on or off.
- When toggling a feature, update the associated elements to correct conformance, including attributes, commands, events, features, and automatically update the feature map attribute according to the configured features.
- When toggling an element, send a warning if it does not conform
- Update Matter XML to include conformance of attributes and commands in CHIP repo

**Description:**

This page should be configurable like Attributes, Commands, and Events. It will list the features supported by each Device Type. Mandatory features should always be enabled in the GUI. Deprecated, disallowed, or provisional features should always be disabled. Optional features should be toggled on or off based on the user's application needs.

**Use Case:**

As a ZAP user creating a Matter application, I want to choose a device type and activate features. Selecting "Features" should show all possible features for the Device Type and allow me to toggle features. The system should automatically set the corresponding bit in the featureMap attribute, and adjust associated Attributes, Commands, Feature, etc. to ensure conformance, eliminating the need for manual configuration.
If a device type feature has complex conformance and doesn't comply after toggling, I should receive a warning and my changes will be disabled, instead of auto-updating elements for me. Changes to the same feature within a cluster and endpoint should sync across multiple device types. If I modify an attribute, command, or feature that causes incorrect conformance, I should receive warnings.

**Requirements:**

**Phase 3:**

- Feature Page also include features from cluster XMLs that are not present in the device type XML. In phase 2, it only supports features defined in the device type XML.
- Move the feature page UI into a per cluster view in parallel with attribute, command, and event page
- Add Vue tutorial and documentation

**Description:**

The functionality remains the same as in Phase 2 but is now extended to include all features, not just device type features. The UI has been redesigned into a more intuitive cluster view, making it easier for users to locate, use, and compare features alongside cluster elements. Additionally, a tutorial will be provided to guide users in understanding and utilizing the project's features effectively.

**Use Case:**

Building on Phase 2, a ZAP user can now toggle any feature defined in the Matter specification, regardless of whether it is directly relevant to a specific device type. Additionally, the feature page has been integrated into the cluster view. User can conveniently check and compare the elements updated by toggling a feature with a single click.

**Technical Details:**

**Database Design:
New Tables:**

- Create a table for Features, including fields for Feature ID, name, description, and conformance.
- Create a table to link Device Types to Features, with fields for Device Type ID, Feature ID, and conformance.

**Data Generation:**

- **Alchemy Generation**: Utilized the automated tool Alchemy to generate conformance data for all attributes, commands, events, and features in CHIP repo and manually fix incompatible places.

**Data Transformation:**

- **XML Extraction:** Developed a parser to extract and translate conformance data from XML into conformance expressions as defined in the Matter specification.
- **Conformance Evaluation:** Created a parser to evaluate the value of a conformance expression based on the state of its terms.

**Front End Integration:**

- Developed Vue components to create the features page, including tables for displaying features.
- Implemented toggles and controls to manage features, with real-time updates reflecting user actions.
- Stored real-time element conformance data to display warnings if feature or element toggles result in incorrect conformance.
- Integrated REST API calls to calculate conformance in the backend and update elements that require changes in the frontend.

**Matter SDK Version Considerations:**

- Older Matter SDK versions has outdated XML files and lack conformance data, which could cause the feature page non-functional.
- To address this, we only display the feature page and related functionalities for newer SDK versions where conformance data exist

**Comment by ethanzhouyc** [comment]
Frontend UI of the Device Type Feature Page
<img width="1600" alt="phase 2" src="https://github.com/user-attachments/assets/b98a95ec-1746-4447-9c06-2b82f83483d0">

**Comment by ethanzhouyc** [comment]
### Phase 2 Example Use Cases:

**1. Enable `HS` feature in an endpoint with `Extended Color Light` device type**

<img width="1294" alt="image" src="https://github.com/user-attachments/assets/1b33e7bc-8411-4053-89c0-df1b0639f731">


**2. After enabling `HS`, disabling attribute `CurrentHue` that conforms to `HS` will cause conformance warnings**

<img width="1600" alt="image" src="https://github.com/user-attachments/assets/23561628-d9e9-4d06-88d1-443597dbd8d6">
