### ISSUE TITLE
Switching to endpoint configuration from the options, extensions and notifications page.

### ISSUE THREAD

**Issue by dhchandw** [project-chip/zap#1382]
- Currently, the only way to go back to a particular endpoint configuration page from the options, extensions and notifications page is by clicking on the back button.

- **Suggested addition** - clicking on a particular endpoint on the left takes the user to the endpoint configuration page of that particular endpoint. 

- This seems intuitive since  the options, extensions and notifications page are not endpoint specific (currently).

- Note: notifications page will be changed to be a panel on the right side identical to the preview page.

<img width="1624" alt="Screenshot 2024-07-31 at 9 17 15 AM" src="https://github.com/user-attachments/assets/56045fdd-2c67-478c-8cd6-6d9faddbffa8">

I'd appreciate any thoughts on this.

**Comment by tbrkollar** [comment]
notification page will not exist in the future. It will be a panel on the right site.

**Comment by paulr34** [comment]
I see a contradiction. The endpoint is still highlighted even though "Options" is Endpoint agnostic

What do you think about removing the highlight in this case. That way your feature will be more intuitive to the user because they are "reselecting" an endpoint and subsequently returning to the "Endpoint" view.

**Comment by dhchandw** [comment]
@paulr34 that makes sense. The endpoint shouldn't be highlighted unless we are on a page that is specific to it. Ideally, when we are on the options page for example, none of the endpoints should be highlighted but clicking on one of the endpoints should take us to the config page for that endpoint. 

I think right now the endpoint that is highlighted just signifies that this is the endpoint config you go back to when you click the back button.
