### ISSUE TITLE
Some commands not displayed in Matter Clusters

### ISSUE THREAD

**Issue by ethanzhouyc** [project-chip/zap#1424]
**Steps to reproduce:**
1. npm run zapmatter
2. create an endpoint on 'Matter Extended Color Light'
3. navigate to 'Color Control' cluster
4. navigate to 'Commands'

**Issue:**
The row number displayed at the bottom of the page is 19, but there are only 12 rows actually shown. The page should show 19 rows because in the XML, there are 19 required commands for the cluster.

**Screenshot:**
<img width="1906" alt="image" src="https://github.com/user-attachments/assets/337b7e67-4612-4d11-b8db-a4bd71ad09e2">

**Comment by paulr34** [comment]
closing because this is completed
