### ISSUE TITLE
Missing Menu bar 

### ISSUE THREAD

**Issue by RichardPar** [project-chip/zap#1430]
The GUI's and howtos show a FILE menu on the top. On the latest and all versions down to just after 2024.08.5 all have this top gone. (On Linux Cinnamon) 

![zap_broken](https://github.com/user-attachments/assets/cd01567a-48fb-47b8-98c4-aca061297f35)

Last version the FILE menu was visible was 2024.08.5
![image](https://github.com/user-attachments/assets/b7654e1d-ed5f-4ce8-914a-6830e3d31d8d)

**Comment by soares-sergio** [comment]
I'm having the same issue.

Tried using the ZAP tool today and I get no menus, there's no way to save my ZAP file changes. See screenshot attached:

![image](https://github.com/user-attachments/assets/91e2258c-c2ef-4d6d-809d-b92e1947c393)

I even tried quitting to see if it would offer me the option to save it, but it just says "Quit anyway", no option to save the zap file changes. See screenshot:
![image](https://github.com/user-attachments/assets/5c3c65fb-e201-4a55-bdda-247b429eaddb)

I'm running the tool using the following command to update the energy-management-app zap file:
```
./scripts/tools/zap/run_zaptool.sh examples/energy-management-app/energy-management-common/energy-management-app.zap
```

Zap version is:
```
$ zap --version
Version: 2024.10.11
Feature level: 104
Hash: d8415780d92050a1e2dc3216fa6e522475ac35de
Date: 2024-10-11T15:20:14.000Z
Mode: source 
```

I'm running on a debian-based linux ` Debian 6.9.10 x86_64 GNU/Linux`

This happened last week as well but a restart of the tool solved the problem. I tried that today and had not luck.

**Comment by soares-sergio** [comment]
Tried rolling back to `v2024.8.27` and it still didn't work.
`v2024.6.4` works fine!

Diff patch if anyone needs:
```
diff --git a/scripts/setup/zap.json b/scripts/setup/zap.json
index 8b18116caa..8051485e12 100644
--- a/scripts/setup/zap.json
+++ b/scripts/setup/zap.json
@@ -8,7 +8,7 @@
                 "mac-amd64",
                 "windows-amd64"
             ],
-            "tags": ["version:2@v2024.10.15-nightly.1"]
+            "tags": ["version:2@v2024.06.04.1"]
         },
         {
             "_comment": "Always get the amd64 version on mac until usable arm64 zap build is available",
diff --git a/scripts/setup/zap.version b/scripts/setup/zap.version
index e58d8c5cac..c950b935e6 100644
--- a/scripts/setup/zap.version
+++ b/scripts/setup/zap.version
@@ -1 +1 @@
-v2024.10.15-nightly
+v2024.06.04
diff --git a/scripts/tools/zap/zap_execution.py b/scripts/tools/zap/zap_execution.py
index 9ed0b0f222..3d8f0c5cfb 100644
--- a/scripts/tools/zap/zap_execution.py
+++ b/scripts/tools/zap/zap_execution.py
@@ -23,7 +23,7 @@ from typing import Tuple
 # Use scripts/tools/zap/version_update.py to manage ZAP versioning as many
 # files may need updating for versions
 #
-MIN_ZAP_VERSION = '2024.10.15'
+MIN_ZAP_VERSION = '2024.06.04'
 
 
 class ZapTool:
```

**Comment by andy31415** [comment]
Bisect says https://github.com/project-chip/zap/pull/1388 is when it started. I can reproduce with `npm run zap` and my menu disappears (but have some hurdles when bisecting as I had to do `npm install` and `npm install -D sass sass-embedded` quite often and without knowing exactly why (except I was getting CSS errors without)
