### ISSUE TITLE
Need a way to classify types based on their "base type"

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#1438]
In the Matter specification, types can have a "base type".  For example, `node-id` is a derived type from the `uint64` base type.

For Matter, it would be useful to code-generate a function that takes a type as input and returns the base type (which may be the type itself) as output.  Unfortunately, at the moment ZAP types do not have base type information attached to them, making this rather difficult.

**Comment by brdandu** [comment]
For more reference: https://csamembers.slack.com/archives/C01B01GH64E/p1727461850620559
