### ISSUE TITLE
Custom ZCL paths are wrong and cannot be changed

### ISSUE THREAD

**Issue by janusheide** [project-chip/zap#145]
By default zcl.json and gen-templates.json points to what appears the files in the zap repo, the paths are:

"path": "../../../../../../zap/zcl-builtin/silabs/zcl.json",
"path": "../../../../../../zap/test/gen-template/zigbee/gen-templates.json",

You cannot add the correct files using zap, it complains (in the terminal) about a wrong file extension, and every time you save it overwrites whatever you set yourselves manually in the zap file.

**Comment by eve-cxrp** [comment]
I had the same issue. My current workaround is calling the zap tool through some scripts.

```
cd $ZAP_REPO
node ./src-script/zap-start.js --logToStdout -z $ZCL_JSON -g $APP_TEMPLATES_JSON -i "$OPT_IN_FILE"
cd - 
```

By calling zap tool in this manner, the tool is able to set the paths correct. Although this is of cause not the "right" way of solving the problem it might be helpfull to you.

**Comment by eve-cxrp** [comment]
Well, I didn't invent this... All I can tell you is that this is used in the CI/CD of the connectedhomeip repo. It seems now to be also wrapped inside a python script:

connectedhomeip/scripts/tools/zap/generate.py
```
def runGeneration(zap_file, zcl_file, templates_file, output_dir):
    generator_dir = getDirPath('third_party/zap/repo')
    os.chdir(generator_dir)
    subprocess.check_call(['node', './src-script/zap-generate.js', '-z', zcl_file, '-g', templates_file, '-i', zap_file, '-o', output_dir])
```

> Unfortunately this does not fix the problem I have, I have a couple of zap files that someone edited by hand, and zap totally clubbers those if I open them and save them again :/

Well, thats the "beauty" of using a tool for generating stuff. You should not edit files by hand.

**Comment by tecimovic** [comment]
Are you talking about these things:
`  "package": [
    {
      "pathRelativity": "relativeToZap",
      "path": "../../../src/app/zap-templates/zcl/zcl.json",
      "version": "ZCL Test Data",
      "type": "zcl-properties"
    },
    {
      "pathRelativity": "relativeToZap",
      "path": "../../../src/app/zap-templates/app-templates.json",
      "version": "chip-v1",
      "type": "gen-templates-json"
    }
  ],
`
These should be recorded correctly, but currently the functionality to automatically load the correct JSON files has not yet been implemented, the system is using whatever you specify via -z and -g.

**Comment by tecimovic** [comment]
It's a known gap right now. We need to add ability to stop passing the "global" templates and zcl files via the `-z` and the `-g` flags, but simply allow zap to read in these files on demand, when the zap file is loaded.

**Comment by janusheide** [comment]
Thanks for the pointers

@eve-cxrp So eventually it turned out that your suggestion solved half my problem, the other half was that I needed to delete the cache in zap.sqlite (because I had been running it without those parameters first), if you dont do that adding those parameters appear to do nothing :/ - but after I did that it started behaiving as intended :)

You are right, those files should not be edited by hand...

So this seem to be a case of a couple of more or less know quirks and a new user...
