### ISSUE TITLE
Add ZAP Support for Commands having the 'LargeMessage' quality  

### ISSUE THREAD

**Issue by pidarped** [project-chip/zap#1457]
From Spec 1.4 onwards Commands may have the quality `L` for Large Message. When this quality is expressed in a cluster xml for a command, ZAP machinery should pick that up and auto-generate SDK code for marking the command as such. This would allow the SDK to utilize that indicator to setup the underlying session appropriately. 
Current quality fields are supported in the cluster xml directly as part of the 'attribute' or the 'command' tag. This quality could also reside within the command tag of the cluster xml as a boolean `isLargeMessage` 
For example:
```
<command code="0x0B" source="client" name="CaptureSnapshot" optional="true" isLargeMessage="true">
  <description> ...
```

**Comment by brdandu** [comment]
For more context also refer to https://csamembers.slack.com/archives/C01B01GH64E/p1728932566576929
