### ISSUE TITLE
Implement ZCL feature bits

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#150]
ZCL has a concept of "feature bits" in the spec, which are the user-conveninent shortcuts to enable/disable sets of attributes or other entities tagged with that feature bit. 

Neither ZAP tool, nor the XML does not support that currently. We need to implement it.

**Comment by tecimovic** [comment]
Ok, I'm trying to comprehend the feature bits, which seem very much connected with the "conformance tags".

So my thought for now:

1.) There is a thing called "conformance tag". These are random 'tags" and currently these seem to be a 2 character things (NV, LK, but they can really be any random strings). So XML loads up the general collection of these tags into some table.

2.) Conformance tags can be used in a form of "expressions" (there is table in chapter 7.3 Conformance in the spec). These expressions can be attached to any entity (commands, clusters, events, attributes?)

3.) In addition to these "expressions", there is also a "FeatureMap" global attribute on a cluster. That attribute maps a certain bit inside this bitmaps to a given "conformance tag". So it can say:
     bit 1 corresponds to conformance tag "NV"
     bit 2 corresponds to conformance tag "LK".

4.) Entire network of nodes, therefore has to agree to the meaning of these tags and the per-cluster mappings so everyone IMPLICITLY knows what "NV" means. And then everyone can query the cluster on a given device in a following way (for example, node 1 wants to understand if node 2 supports "NV" tag:
          a.) node 1 asks node 2: "Can you give me the value of your FeatureMap attribute for cluster X?"
          b.) node 2 sends back the value of FeatureMap attribute.
          c.) node 1 then looks up this value, and maps it with this knowledge of "bit 2 corresponds to the NV tag" which comes pregeenrated from XML.
          d.) this then gives node 1 the answer if the node 2, cluster X, supports the tag "NV".

@bzbarsky-apple , @lazarkov , @mrjerryjohns : do I comprehend this correctly?

**Comment by tecimovic** [comment]
My XML+schema first thought for this is:

1.) Have a TAG table, which contains name+description of the conformance tags. These are created via some global element in XML:
   <tag name="AB" description="Description of this tag"/>
   
2.) Expand the current `<globalAttribute>` tag with <featureMap bit="n" code="AB">. Given that these are recorded into a "FeatureMap" attribute, it makes sense that this is managed via a default value for a global attribute per cluster, which is already present inside the <globalAttribute> tag inside a cluster. So in essence this approach simply defines a value for a global attribute, but it gives it a structure.

3.) Add a table "GLOBAL_ATTRIBUTE_BIT" which is attached toi a "GLOBAL_ATTRIBUTE_DEFAULT" and stores this per-bit linkage to the TAG table, so you essentially store the data: "bit 1  <=> tag AB", "bit 2 <=> tag LK", etc.

@lazarkov : You have suggested something like this:

<feature code="NK" bit="2" name="Number Keys" description="Supports numeric input 0..9">true</feature>
   
Am I incorrect in thinking that the `name` and `description` here should be global, since EVERY cluster that will want to turn on the `NK` tag will have to have the same `name`/`description` carrying along? 
Hence my idea from above that we need a separate place where we DEFINE these tags and the individual cluster will only put this inside it's global attribute definition for the FeatureMap attribute:
    <feature code="NK" bit="2">true</feature>

If you type a `code` here that is never declared globally in XML, the loader would throw an error.

**Comment by jmeg-sfy** [comment]
Definitively need this requirement since some clusters highly rely on the feature map for their behavior

**Comment by lazarkov** [comment]
@tecimovic Can it be tied to cluster when xml is being imported to SQL schema?
To my understanding, feature bits are cluster specific, there won't be global feature bits shared between clusters.

**Comment by tecimovic** [comment]
Yes, these are per-cluster default values of a global attribute.

My implementation currently is:
```
 <cluster>
    <name>Network Provisioning</name>
    <domain>CHIP</domain>
    .
    .
    .
    <globalAttribute side="either" code="0xFFFC" value="0x0055">
      <featureBit tag="F0" bit="0">true</featureBit>
      <featureBit tag="F1" bit="2">false</featureBit>
      <featureBit tag="F2" bit="4">true</featureBit>
      <featureBit tag="F3" bit="6">false</featureBit>
    </globalAttribute>
    .
    .
    .
  </cluster>
```

**Comment by tecimovic** [comment]
This is done, closing the issue.
