### ISSUE TITLE
Support complex types

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#151]
Zap and the silabs XML is lacking support for complex data types. We need to add and implement that.

Minimum required list of features:

-  use type 'ARRAY' to specify list type within 'attribute' or 'command', with a user defined struct being an element of the array.
- allow nested structs: a struct that contains another struct.
- allow support for the maximum length of lists and arrays, and generation of code that enforces these maximums.
- allows support for attributes of the type "struct". Provide ability to specify complex default values and ability for the UI to edit them.

Support arbitrary nesting of structs, etc.

Access-control qualities (read spec).

**Comment by brdandu** [comment]
@tecimovic , @bzbarsky-apple I feel like we can close this issue. Are there any types which that currently cannot be handled?

**Comment by bzbarsky-apple** [comment]
As far as I am concerned this is done.

**Comment by brdandu** [comment]
Closing this issue since we support complex types in some form or way. If another type is required then let's create a separate issue for that.
