### ISSUE TITLE
Save is still not fully functional

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/zap#159]
#155 addressed a similar problem. After some discussion with @tecimovic we have identified the problem:

When opening the zap file in the following manner:

`node ./src-script/zap-start.js --logToStdout -z $ZCL_JSON -g $APP_TEMPLATES_JSON -i "$OPT_IN_FILE"`

and editing the zap file and pressing `ctl+s` the zap tool still presents an error:

```
{"level":50,"time":1622040654554,"pid":85940,"hostname":"meow","name":"zap","msg":"Unable to save project with sessionId(1)"}
{"level":50,"time":1622040654554,"pid":85940,"hostname":"meow","name":"zap","msg":{"errno":-2,"code":"ENOENT","syscall":"open","path":""}}
```

Currently there is a workaround for this:

In the UI use the `File -> Save As...` dialog to save the changes.

**Comment by tecimovic** [comment]
Ok, a new PR has been merged to master. This should be fixed now.
