### ISSUE TITLE
When templates have errors, report location in file where the error happens.

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#165]

**Comment by tecimovic** [comment]
@bzbarsky-apple : You were asking for this. It's now done on `master` branch: when an exception is thrown from the helper, the wrapper-helper function gathers the line of template where this happens and prints it out, like this:
`⚠️  Errors:
    👎  tmp/test-fail.out: ⛔ Error: this is where the failure lies [line: 3, column: 0, file: /home/timotej/git/zap/test/gen-template/test/test-fail.zapt ]
`

**Comment by tecimovic** [comment]
You can test it via `npm run gentest`:
   see test template `test/gen-template/test/test-fail.zapt` for the failure test.

**Comment by bzbarsky-apple** [comment]
@tecimovic Thank you!
