### ISSUE TITLE
Work for immediate CHIP support: events, TLVs, etc

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#168]
This work covers the discussion we had with @andy31415 on 6/8/2021.

To-do items:
 

- [x] Add the support for TLV-based structs:
     - extend XML shema for Silabs XML files (no need to do anything with dotdot)
     - extend SQL schema
     - fix the queries 
     - provide basic helpers.
     - prevent loading of mixed case: some fields have ID some don't.
     - allow initial loading of structs without IDs, gated by zcl.json preference.
     - Call these "FIELD_ID" not "ORDINAL", or "TAG".
NOTE: MIND THE MANUFACTURER SPECIFIC STUFF! (Read up on spec.) 

- [x] Add the support for CHIP "events" (attributes with history?)
    - understand the spec
     - extend XML shema for Silabs XML files (no need to do anything with dotdot)
     - extend SQL schema
    - fix the queries
    - provide basic helpers

- [x] Add the support request/response metainfo (or "return value" for the requests, however you see it).
     - extend XML shema for Silabs XML files (no need to do anything with dotdot)
     - extend SQL schema
     - fix the queries 
     - provide basic helpers.

- [x] Feature map support.

**Comment by andy31415** [comment]
Terminology update from @mrjerryjohns 

- TLV is the actual encoding and we want to have the definitions of things to be encoding-agnostic. We need "FieldId" naming-wise (which is required)

For CHIP code review needs, we have to be able to quickly compare "does this match spec" so we need zap to be concise for clusters and endpoints. This includes not duplicating xml data (only deviation) and also not having extra placeholder items (In endpoints I see "Anonymous endpoint type" as name and similar ... these should not be required).

**Comment by tecimovic** [comment]
@andy31415 , @mrjerryjohns :
   we already have an ORDINAL column in the database. 
   This column is present for:
      - command fields
      - bitmap fields
      - enum items
      - struct fields

Is the TVL "FieldID" trully different from this "ORDINAL"?

We are currently populating 'ORDINAL' from the natural sequence of these field being present in the XML files, starting with 0 for the first item and so on. It is just used in queries to ensure sorting by this natural order.

Is the FieldID for your items that require it different than this "ORDINAL" number?

**Comment by tecimovic** [comment]
So if this represents more or less the same data, then I'll just add an ability to XML to be able to specify `fieldId="xyz"` in the XML, in cases where you want to override the natural ordering fieldId, that gets put in the DB otherwise.

**Comment by tecimovic** [comment]
@andy31415 : PR https://github.com/project-chip/zap/pull/169 contains the request/response mechanism, linking "response" commands with the corresponding "request". I will merge it into `master` imminently if all unit tests pass.

**Comment by tecimovic** [comment]
```
    <command source="client" code="0x01" name="SaveStartupParameters" optional="true">
      <response>
        <cmd name="SaveStartupParametersResponse"/>
        <cmd name="SaveStartupParametersResponse2"/>
        <cmd name="SaveStartupParametersResponse3"/>
        <cmd name="SaveStartupParametersResponse4"/>
      </response>
```
This is the kind of structure I plan to put into the XML to record multiple response commands possible.
`<response>`is optional, and may have one or more `cmd` tags.
This allows us to put something else under `<response>` in the future, such as 
`<defaultResponse/>` or something like that.

**Comment by tecimovic** [comment]
I moved the "access qualities" and "make zap smaller" into separate issues, so we have better tracking.

**Comment by tecimovic** [comment]
Closed in https://github.com/project-chip/zap/pull/175
