### ISSUE TITLE
Provide full and clean abstraction of IDE integration

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#172]
ZAP contains "IDE integration" feature.

What it does is the following:
   a.) ZAP may run standalone, without any IDE integration.
or
   b.) ZAP may run in "IDE integration" mode.

When running in IDE integration mode ZAP is aware of an IDE it lives in so it can possibly communicate with other parts of the system. Canonical example:
   if ZAP runs inside Simplicity Studio, then when you enable a cluster inside ZAP, zap informs Simplicity Studio to turn on the C component that actually IMPLEMENTS that cluster.
   
This functionality needs to be abstracted, so that this works also in other IDEs, most notably VSCode.

So the goal of this issue is to provide a clean abstraction point, where different IDE integration implementations can plug in cleanly.

This already builds upon existing IDE integration with Simplicity Studio, however the point is to clean this up, after some code review revealed that the integration point is currently not cleanly abstracted.

**Comment by tecimovic** [comment]
@jingteng25742 ^^

**Comment by jingteng25742** [comment]
This ticket has been created a while ago and RendererAPI has been created to serve this purpose. 
Studio currently utilizes the RendererAPI mechanism for integration.
VSCODE integration has been on the back burner for a quiet.
Closing this issue until VScode integration is restarted again.
