### ISSUE TITLE
.zap files are too large and contain redundant data

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#173]
"Shrink" the .zap files, essentially eliminating duplication. Go back to the model of "only record deviations, not the whole duplication". So if ZAP file is using the default Basic cluster, for example, it will NOT record duplications of all attributes that are mandatory anyway. It will only record the data BEYOND what the spec already lists.

**Comment by jingteng25742** [comment]
Should .zap capture the version of xml it is complying with for "versioning" purpose?
Otherwise, what happens when the XML are updated and the .zap's "baseline" is essentially changed?

**Comment by brdandu** [comment]
Based on our discussion, we can have a save as option which just saves the enabled content in the zap file. The saved options should follow the hierarchy in the following order:
1) endpoint
2) cluster
3) attribute and commands

For eg:
- If 1 is not enabled then we should lose 2 and 3 from the json file.
- if 2 is not enabled for an endpoint then lose 3 from the json file

**Comment by brdandu** [comment]
Resolved in https://github.com/project-chip/zap/pull/1153
