### ISSUE TITLE
Add support for Qualities - specifically access control qualities

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#174]

**Comment by brdandu** [comment]
Is this still an issue? What are access control qualities?

**Comment by lpbeliveau-silabs** [comment]
@brdandu Various qualities are described in the section 7.7 of the main matter spec (regarding the quality column of attributes)

**Comment by bzbarsky-apple** [comment]
Access control bits are all supported already, fwiw.

**Comment by bzbarsky-apple** [comment]
What's missing is for attributes to track whether they can be part of a scene.

**Comment by lpbeliveau-silabs** [comment]
That should be accomplished by the Quality column if I understood the spec correctly, so shouldn't the other Quality flags (X, N, F, S,P,C, I and !Q) be supported as well?

**Comment by bzbarsky-apple** [comment]
X is supported.  N is supported.  What would "supported" mean for F?  P does not do anything in Matter. I does not do anything in Matter, really; it's there in Zigbee for the Basic cluster, which is not part of Matter.  Device types are not really well-represented in the ZAP XML, so !Q has no way to be represented right now.

**Comment by lpbeliveau-silabs** [comment]
It seems there was a misunderstanding on my part, I assumed a "quality" field was supposed to be implemented in zap. I agree that currently Scene is the attribute that would need support in the immediate as it should be implemented for matter 1.2.

**Comment by brdandu** [comment]
Trying to connect the pieces together here, I see that the xml has some quality related updates for attributes and struct fields with a scene attribute that is just a boolean. Is there more to this apart from an attribute's scene being true/false? Can anyone point me to an example use case to wrap my head around this?

**Comment by brdandu** [comment]
@lpbeliveau-silabs @bzbarsky-apple can this be resolved with the solution provided in https://github.com/project-chip/zap/issues/980 ?

**Comment by brdandu** [comment]
This has been resolved in https://github.com/project-chip/zap/issues/980
