### ISSUE TITLE
Expand "custom XML" feature into "custom package" feature

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#191]
We have a feature where end-user can add "custom XML" which adds entities to the DB so that they can use them in the UI and zap files and such.

However, at this point we don't have an ability to add "package extensions" or even additional .zapt templates from the end-user.

We need to modify this feature in a following way:
   1.) Toplevel file read in is no longer just a ZCL XML file, but some kind of "custom.json" file or something.
   2.) This file can point to any number of the ZCL XML files.
   3.) This file can point to any number of the gen-templates.json files (or just contain data directly.)
   4.) Through 3, the package can also contain package extension JSON files or additional .zapt templates.
   
It would be nice if the code would be able to just take a .zip file as an input and disentangle all this from a single zip file.

**Comment by brdandu** [comment]
This seems similar to https://github.com/project-chip/zap/issues/780 . Closing this as a duplicate.
