### ISSUE TITLE
int16S limit checks error

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/zap#208]
When setting any of the thermostat setpoint limits (int16s) a warning is always generated for value being out of range. Correct code is generated though.
![zap_int16s](https://user-images.githubusercontent.com/33329862/129589564-5eedfd53-837f-4448-b06b-7ba9388276b4.png)

**Comment by tecimovic** [comment]
This seems completely broken...

I go to Temperature Measurement, which has int16s:
![image](https://user-images.githubusercontent.com/7923190/150847792-d37ce1cc-d571-4bbf-a9a9-fdbe1d539abf.png)

I observe the following:
1.) I can type a number 13 into one of the INT16S fields, and they don't save at all.
2.) The moment I get to that page, I see exceptions:
```
⇝ (node:2188796) UnhandledPromiseRejectionWarning: ReferenceError: isValidSignedNumberString is not defined
    at validateSpecificAttribute (/home/timotej/git/zap/src-electron/validation/validation.js:79:7)
    at Object.validateAttribute (/home/timotej/git/zap/src-electron/validation/validation.js:38:10)
    at /home/timotej/git/zap/src-electron/rest/user-data.js:210:26
(Use `electron --trace-warnings ...` to show where the warning was created)
⇝ (node:2188796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2188796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by tecimovic** [comment]
I have no idea what's going on, but there is no validation happening, numbers are not saving and exceptions are coming from back-end.
Please take a look.
