### ISSUE TITLE
Ranges not being generated by zap

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/zap#209]
Problem
Thermostat.xml file contains the min and max values for
Temperature setpoints and limits but they do not appear in the generated .zap file
These were identified in #8878

Also the zap tool displays warnings about signed ints but does generate the correct code.

Matter spec seems to have removed the ranges

Proposed Solution
Follow up on these

**Comment by jmeg-sfy** [comment]
I think this is almost everywhere the same issue

**Comment by bzbarsky-apple** [comment]
@chrisbeach59 I believe https://github.com/project-chip/zap/pull/330 fixed this.

**Comment by bzbarsky-apple** [comment]
Er, didn't mea to close.  @chrisbeach59 please close if this now works as you expect?

**Comment by chrisbeach59** [comment]
@bzbarsky-apple OK To Close.  I don't have rights to do so. 
Thanks
