### ISSUE TITLE
Need zcl_structs per Cluster Id API

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#219]
Currently zcl_structs  use selectAllStructsWithItems, which retrieve all structs for all clusters, for chip complicated type representation, we expect zcl_structs is able to retriever structs per cluster, which similar to functionality selectCommandsByClusterId API

**Comment by tecimovic** [comment]
@yunhanw-google 

What is a "struct per cluster"?

Structs are just a generic bucket of types in the current schema. How are they linked to a specific cluster?
Command, on the other hands are tied to clusters, so that's not a problem, but for structs they are currently just global.

Should we add a linkage to the structs to make them cluster-specific?

**Comment by yunhanw-google** [comment]
yes, I think we should add a linkage to the structs to make them cluster-specific

**Comment by tecimovic** [comment]
This has been fixed on PR https://github.com/project-chip/zap/pull/224.

Examples of how to use it:

   - see test/resource/meta/types.xml for example of how to put <cluster> tag in there. You can have zero or more of them.
 ```
  <enum name="TestEnum" type="ENUM8">
    <cluster code="0xABCD"/>
    <item name="A" value="0x00"/>
    <item name="B" value="0x01"/>
    <item name="C" value="0x02"/>
    <item name="D" value="0x03"/>
    <item name="E" value="0x04"/>
  </enum>

  <struct name="SimpleStruct">
    <cluster code="0xABCD"/>
    <item name="a" type="UINT8U"/>
    <item name="b" type="BOOLEAN"/>
    <item name="c" type="ENUM8"/>
    <item name="d" type="OCTET_STRING"/>
    <item name="e" type="CHAR_STRING"/>
  </struct>   
```

- see test/resource/meta/struct-and-enum-by-cluster.zapt for how to use it in a template:
```
This file goes over all the clusters and then outputs structs and enums
for each of the clusters.
{{#zcl_clusters}}
Cluster: {{name}}

Structs for cluster {{name}}:
{{#zcl_structs}}
   * Struct: {{name}}
{{#zcl_struct_items}}
      - item: {{name}}
{{/zcl_struct_items}}
{{/zcl_structs}}

Enums for cluster {{name}}:
{{#zcl_enums}}
   * Enum: {{name}}
{{#zcl_enum_items}}
      - item: {{name}}
{{/zcl_enum_items}}
{{/zcl_enums}}


{{/zcl_clusters}}

```
