### ISSUE TITLE
Migrate SETTINGS table when recreating schema

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#223]
When schema changes, zap will wipe out the DB and reload it from scratch.

This looses the SETTINGS table, which are local per-install settings.

Add following to the process of changing the scheme:
  - before wiping out old schema, do a full SELECT on the SETTINGS table.
  - perform the wipe-out as now.
  - load back the data from earlier SELECT query into the new SETTINGS table.

**Comment by tecimovic** [comment]
The purpose of this bug, is to keep the SETTINGS that were added previously, even when schema is recreated.

Note that there are 3 "special" settings:
   APP/VERSION, APP/HASH and APP/DATE.
Those are wrritten into the SETTINGS table by design, every time zap starts, to record the version of the zap that ran against this databse. These three are ok to not persist. They are intended to keep growing.

The settings that should persist are other category/key/value triplets.

For example, if the SETTING table contains:
   category=METAFILE
   key=ZCL_XML_LOCATION
   value=/home/user/some/place/zcl.xml
(made these up as example), then the expectation is, that after the schema is recreated, the SETTING table will still contain this triplet.

There are several values we wanted to put into this table, but we mostly didn't because they all get wiped out every time schema changes.

**Comment by paulr34** [comment]
merged PR https://github.com/project-chip/zap/pull/486
