### ISSUE TITLE
Need one API to tell if underlying type is supported/known or not

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#230]
currently asUnderlyingZclType can do some transformation for basic type, for example, from UINT16U to uint16_t, for unknown type, it convert it to uint8,

is that possible to have similar API, that API can return unknown string or false if that input type is not known.

**Comment by brdandu** [comment]
> currently asUnderlyingZclType can do some transformation for basic type, for example, from UINT16U to uint16_t, for unknown type, it convert it to uint8,
> 
> is that possible to have similar API, that API can return unknown string or false if that input type is not known.

Data type schema rework is being done. I can add a helper which check if the type name being searched actually exists in the db or not. Would that solve your purpose?

**Comment by brdandu** [comment]
Closing this since you should now get an error if a certain data type is not found in the available data types from the xml.
