### ISSUE TITLE
asUnderlyingZclType returns uint8_t for any type under zcl_struct_items

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#232]
If I try to use asUnderlyingZclType type under zcl_struct_items
it prints TYPE WARNING: array array defaults to uint8_t, which looks not right.

**Comment by brdandu** [comment]
Does {{as_underlying_zcl_type type array="uint8_t *"}} work for you? You can overwrite an array type like this.

**Comment by yunhanw-google** [comment]
it does not work. using  {{as_underlying_zcl_type type array="uint8_t *"}}, it would print something  * TYPE WARNING: INT32U array defaults to */ uint8_t * or /* TYPE WARNING: INT8U array defaults to */ .....and looks like cannot overwrite..

**Comment by brdandu** [comment]
@yunhanw-google,  https://github.com/project-chip/zap/pull/476 PR should fix this issue. I can update you once it has been merged.

**Comment by brdandu** [comment]
Closing this since it has been resolved now.
