### ISSUE TITLE
Add Ability to process enum and struct when moving all enum and struct inside cluster.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#234]
Per @tcarmelveilleux suggestion , all enums and structs in Matter clusters are single-cluster-use, we can consider to move those inside cluster category, we need the corresponding zap support.

**Comment by brdandu** [comment]
@yunhanw-google is this resolved?

**Comment by brdandu** [comment]
Closing this. Assuming this is not an issue anymore and has been resolved.
