### ISSUE TITLE
Double Array detection for struct item

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#237]
```
<struct name="DoubleNestedStructList">
    <cluster code="0x050F"/>
    <item name="a" type="NestedStructList" array="true" optional="false"/>
  </struct>

```
NestedStructList is also an Array

for array, we need to generate code DataModel::DecodableList<NestedStructList::DecodableType> a;
instead of
 DataModel::DecodableList<NestedStructList::Type> a;

I am not sure how to recognize NestedStructList is list in DoubleNestedStructList struct since DoubleNestedStructList don't have the type knowledge about NestedStructList
we may need to amend xml to add something "doubleArray" or innerType="Array" then zap know how to handle the embedded array type

wanna check if the above thought is right, it looks like we have to do something magic in xml to tell if the inner item is list for struct array inner item

**Comment by tecimovic** [comment]
Does "IS_ARRAY" not serve this. So you have an ARRAY of LISTS here?

**Comment by yunhanw-google** [comment]
yep, currently a array of list

**Comment by tecimovic** [comment]
Where do you declare "NestedStructList"?

**Comment by yunhanw-google** [comment]
https://github.com/yunhanw-google/connectedhomeip/blob/c8eed6b38b21b19226746f56cb517eb29bed49a8/src/app/zap-templates/zcl/data-model/chip/test-cluster.xml#L49

**Comment by yunhanw-google** [comment]
```
  <struct name="NestedStructList">
    <cluster code="0x050F"/>
    <item name="a" type="INT8U" optional="false"/>
    <item name="b" type="BOOLEAN" optional="false"/>
    <item name="c" type="SimpleStruct" optional="false"/>
    <item name="d" type="SimpleStruct" array="true" optional="false"/>
    <item name="e" type="INT32U" array="true" optional="false"/>
    <item name="f" type="OCTET_STRING" array="true" optional="false"/>
    <item name="g" type="INT8U" array="true" optional="false"/>
  </struct>

  <struct name="DoubleNestedStructList">
    <cluster code="0x050F"/>
    <item name="a" type="NestedStructList" array="true" optional="false"/>
  </struct>
```

**Comment by yunhanw-google** [comment]
NestedStructList has array inside
DoubleNestedStructList has array of NestedStructList

**Comment by yunhanw-google** [comment]
or we could have the API,in DoubleNestedStructList,  check if NestedStructList in struct pool is has a array or not

**Comment by tecimovic** [comment]
1.) make sure you start your toplevel zcl_structs like this: `{{#zcl_structs checkForDoubleNestedArray="true"}}`
 2.) If you do, then inside the block you can use struct_contains_nested_array variable, which can be true or false.
