### ISSUE TITLE
The maximum value for unit64 is not correct

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/zap#244]
For the attribute defined as 64 bits 0 value, but min/max interval is 1..65534. For example

`<attribute side="server" code="0x0C" define="OVERRUN_COUNT" type="INT64U" min="0x0000000000000000" max="0xFFFFFFFFFFFFFFFF" writable="false" default="0x0000000000000000" optional="true">OverrunCount</attribute>`
  
  The generated code is 

            {
              "name": "OverrunCount",
              "code": 12,
              "mfgCode": null,
              "side": "server",
              "included": 1,
              "storageOption": "RAM",
              "singleton": 0,
              "bounded": 0,
              "defaultValue": "0x0000000000000000",
              "reportable": 0,
              "minInterval": 1,
              "maxInterval": 65534,
              "reportableChange": 0
            },

**Comment by thuctran289** [comment]
The max interval in this case pertains to the amount of time between reports, and not the actual maximum value that the attribute can take on.

**Comment by bzbarsky-apple** [comment]
@yufengwangca Is this still relevant?

**Comment by brdandu** [comment]
Closing this. Please re-open if this is still an issue.
