### ISSUE TITLE
Make asUnderlyingZclType return actual BITMAP potential unsigned type if encountering array of BITMAP 

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#248]
<bitmap name="AlertStructure" type="BITMAP24">
    <field name="AlertId" mask="0x0000FF"/>
    <field name="Category" mask="0x000F00"/>
    <field name="PresenceRecovery" mask="0x003000"/>
  </bitmap>

<arg name="alertStructures" type="AlertStructure"/>
if using asUnderlyingZclType type, it can return uint24_t, 

<arg name="alertStructures" type="AlertStructure" array="true"/>
if using asUnderlyingZclType type, it can recognize the type...I would like to see it return uint24_t..

**Comment by bzbarsky-apple** [comment]
@vivien-apple
