### ISSUE TITLE
Need to expose more information about command responses

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#253]
There's a `response=` thing in XML, but the resulting data is not exposed in useful ways via helpers.  From Slack:

> Boris Zbarsky: Basically, what we want is to have a way to ask "does this have a non-status response?" and a way to ask for that response in some form; minimally for the label or something. 
>
> Timotej Ecimovic: yeah..... It (`{{zcl_commands}}` inside `{{zcl_clusters}}`) calls: `queryCommand.selectCommandsByClusterId` which does:
````
    SELECT
      COMMAND_ID,
      CLUSTER_REF,
      CODE,
      MANUFACTURER_CODE,
      NAME,
      DESCRIPTION,
      SOURCE,
      IS_OPTIONAL
    FROM COMMAND WHERE CLUSTER_REF = ?
    ORDER BY CODE`,
````
> So this specific query is omitting RESPONSE_REF :disappointed:
>
> I'll add it in....
>
> Boris Zbarsky: Yep, so is not grabbing that field.
>
> Timotej Ecimovic: I'll add that in.
>
> Boris Zbarsky: But in any case, sounds like the response ref would let me answer the boolean question but not get useful info about the response if there is one, right?
> Timotej Ecimovic:  It would contain a cryptic integer, or be a null, yeah. So you could do an if. But I would need to add you some kind of `{{commandResponse ...}}` helper to dig for actual useful data.
> So you would do:
````
{{#if responseRef}}
  {{commandResponse name}}
  {{commandResponse someOtherStuff}}
{{/if}}
````
> Something like this...
>
> Boris Zbarsky: So in `src/app/zap-templates/common/ClustersHelper.js` we have these bits:
````
command.isResponse                    = command.name.includes('Response');
````
> and
````
    const response = commands.find(filter);
    if (response) {
      command.hasSpecificResponse = true;
      command.responseName        = response.name;
      command.response            = response;
    } else {
      command.hasSpecificResponse = false;
      command.responseName        = 'DefaultSuccess';
      command.response            = { arguments : [] };
    }
````
> So yes, the above template builds would be helpful.  And if we can replace the logic in function enhancedCommands in that helper file with DB queries that would be helpful too.

@tecimovic

**Comment by brdandu** [comment]
@bzbarsky-apple is this resolved now?

**Comment by bzbarsky-apple** [comment]
Yes, now we are getting the info we want.
