### ISSUE TITLE
Need array support for Event

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/zap#260]
We need array of items for Event field, for example we wanna set the below array=true for event field.

    <event code="0x0001" name="TestEvent" priority="info" side="server">
      <description>Example test event</description>
      <field id="1" name="arg1" type="INT8U"/>
      <field id="2" type="NestedStructList" array="true"/>
    </event>

which would be similar to command args
    <command source="server" code="0x03" name="TestStructArrayArgumentResponse" optional="false" disableDefaultResponse="true">
      <arg name="arg1" type="NestedStructList" **array="true"**/>
    </command>

When taking a look the zcl-loader-silabs.js, it seems it cannot handle array of type.
      if ('field' in event) {
        ev.fields = []
        event.field.forEach((field, index) => {
          if (field.$.removedIn == null) {
            ev.fields.push({
              name: field.$.name,
              type: field.$.type,
              fieldIdentifier: field.$.id ? parseInt(field.$.id) : index + 1,
              introducedIn: field.$.introducedIn,
              removedIn: field.$.removedIn,
            })

**Comment by tecimovic** [comment]
Fixed as part of the PR https://github.com/project-chip/zap/pull/259
