### ISSUE TITLE
Add summaries

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#280]
As I'm using UI for real, I constantly ask myself: "How many clusters have I selected?" "How many attributes have I selected?" "How many reporting attributes are selected?"

etc.

 

As it is now in UI, I can get those numbers through a lot of scrolling and a lot of counting.

I would really like to find a global area in the UI, in some header, which would contain this information:
  1. Total number of clusters (and broken down per client and server) are selected.
  2.) Summary at the each cluster level: How many commands and attributes are selected?
  3.) Global summary: total number of commands and clusters?
  4.) Total sizes: size of attribute table, size of reporting table.
etc.

You get the point. It would be really good if this UI would give me some overal stats for the data.

**Comment by babakzarrinbal** [comment]
Dear @tecimovic 
i'm not sure this is intended or not but 
if you create multiple endpoints their enabled clusters and attributes merges 
i think this is a bug and resolving it requires some basic change on how each endpoint data is stored

**Comment by tecimovic** [comment]
There was a change made recently by @jingteng25742 that was doing something with the endpoints. I need to take a look at it. What exactly do you see?

**Comment by babakzarrinbal** [comment]
@tecimovic 
i don't think it's related to change 
you see the selected clusters and attributes are all saved in one array 
and when we create two end point this array is filled 
so we need to change the way these variable saved 
we can discuss this in meeting so we both have better overview of what is required ... :)

**Comment by tecimovic** [comment]
Ok. We'll talk.
