### ISSUE TITLE
Reporting - Report Required table column

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#284]
The ZCL8 spec defines that reporting is required to be supported for certain attributes, e.g. the On/off cluster's attribute 0x0000 (on/off state).

There is no column in the Attribute Reporting table to indicate which attributes are required to support reporting.

**Comment by babakzarrinbal** [comment]
as of now i've got bellow fields for each attributes
for making a mandatory reportable attribute I now just using is required attribute but don't think it's the one i should rely on ...
any comment on this one ?

list of available info for each attribute :
        "id": 101,
        "clusterRef": 21,
        "code": 7,
        "manufacturerCode": null,
        "name": "power source",
        "label": "power source",
        "type": "enum8",
        "side": "server",
        "define": "POWER_SOURCE",
        "min": "0x00",
        "max": "0xFF",
        "reportMinInterval": null,
        "reportMaxInterval": null,
        "reportableChange": null,
        "reportableChangeLength": null,
        "isWritable": false,
        "isNullable": false,
        "defaultValue": "0x00",
        "isOptional": false,
        "isReportable": false,
        "isSceneRequired": false,
        "entryType": null

**Comment by tecimovic** [comment]
I think `isReportable` is what controls if the attribute should be reportable or not.

**Comment by babakzarrinbal** [comment]
that's what i'm talkin about 

we don't filter attributes in report tab based on isReportable ( all isReportable that i've seen is false) if this is the case,
so i don't actually have "attribute is reportable" field 
also i don't think we have "attribute reportability is madatory " field also ...
i've set the warning based on type of attribute INT8U INT16U etc... and the input as number to check ..
**### will this suffice or should i do other validity check (this is my actual question) ??**
