### ISSUE TITLE
Attributes - disabled attribute config fields are suppressed

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#286]
For an Attribute that is not enabled, the values of some of its config fields (Storage Option, checkboxes, Default value) are not displayed.

If the attribute is enabled (turned On), the values are now shown.

If an enabled attribute is disabled (turned Off), the values of is config fields remain displayed; they are not suppressed as they were initially.

What is the intention / benefit of suppressing display of a disabled attribute's config values? Should either make it behave consistently, or abandon it and always display attribute config values regardless whether the attribute is enabled or not.

**Comment by rerasool** [comment]
Hey @tecimovic, I discussed with Jason and Jing, we think that the fields for each attribute should always be displayed and visible, regardless whether the attribute is enabled or disabled. The option for each field should be pre-filled or preselected.

**Comment by wehale** [comment]
I believe this is still broken. If an attribute is disabled I should not be able to manipulate its values. It seems now I a can manipulate the values of an attribute once I enable it even if I then disable it.
