### ISSUE TITLE
Cluster filter - functional

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#289]
Is there a clear specification of what transitions between the cluster filter dropdown selections are supposed to do? When switching between endpoints, the current setting of the cluster filter does not seem to be applied correctly in all. The cluster table display should be fully refreshed per filter setting to provide the expected and consistent content.

For example with Z3Light, which has three endpoints. Select EP1 and set the filter to "Only Enabled". The subset of cluster categories having enabled clusters is expanded and those clusters are displayed.

Now switch to EP3, a Green Power endpoint. EP3's only enabled cluster is the Green Power cluster in the GP category. Only the GP category is shown, as expected, but it is not expanded to display he Green Power cluster (presumably because it was not expanded when EP1 was selected).

Additionally: after selecting filter for All Clusters or Only Enabled, setting the filter back to "No Filter" doesn't have any effect. Should it?

**Comment by Mehradml** [comment]
Dear @tecimovic do we have updates on the last section of this issue from Jason?

**Comment by jperreault20** [comment]
@Mehradml I think you are asking about what should happen when setting filter selection back to "No Filter"? Sorry, I don't have any further clarification. It was my observation when exercising the filter dropdown, but I am not clear on what the behavior is supposed to be (or perhaps it was not considered / specified).

**Comment by tecimovic** [comment]
The whole interaction of that filter is just plain weird in my opinion.

**Comment by jingteng25742** [comment]
Closing ticket as issue has been verified / fixed.
