### ISSUE TITLE
Cluster ID / Id

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#292]
In various places where Cluster ID is mentioned or shown as a column heading, the text is inconsistent in its use of ID v. Id.

**Comment by SaharKargar** [comment]
@tecimovic
Dear Timotej, I had a quick question just to make sure we are on the same page.
So there are some places that we have "cluster Id" as the text of column headings.
We just have to change it to "Cluster ID" right?

**Comment by tecimovic** [comment]
Looking at the ZCL spec, they actually pretty consistently use the full work "Identifier" and are not trying to abbreviate into "ID" or "Id". Let me run this by some folks that are closer to documentation and such...

**Comment by tecimovic** [comment]
I ran this question with the documentation folks...

We should always use "ID" as in all uppercase.
But if we have real estate we can use a full word "identifier".

So for sake of simplicity, it should be "Cluster ID", "Command ID", "Attribute ID", etc for now.
If you are updating something that is a full sentence, as in some paragraph, then we could use "identifier" instead of the abbreviation. Make that decision based on real estate.
