### ISSUE TITLE
Responsiveness of the preview pane and endpoint component

### ISSUE THREAD

**Issue by brdandu** [project-chip/zap#296]
The preview pane and the endpoint component are not very responsive based on screen size. It would be nice if scale them like the other pieces of the UI

**Comment by babakzarrinbal** [comment]
dear @tecimovic 
the preview is responsive ( in contrast of the total UX) 
i don't fully understand what is needed , can you elaborate more on this please

**Comment by tecimovic** [comment]
It's a resize issue. Fidget with resizing.

**Comment by babakzarrinbal** [comment]
ok so i resolved another error on the page to find there is a bug with quasar drawer with cause the panel to get hidden in certain resize scenarios and I can't override the method 
options:
update quasar when they fixed it 
    pros: standard, clean , not much effort from our side
    cons: with update they may change some stuff we need to deal with in other part of app
create new drawer component and use it instead
   pros: own code base, no such issue will remain unsolved
   cons: not standard, time consuming for us

**Comment by jingteng25742** [comment]
@brdandu 
Testing the mentioned scenario with the latest new UI, I am not seeing the laggy issue anymore. 
Feel free to re-open if you're still experiencing this issue.
