### ISSUE TITLE
UI cleanup within cluster cleanup

### ISSUE THREAD

**Issue by brdandu** [project-chip/zap#298]
When we open 'configure' on a cluster, on the top we see something like:
```
< Endpoint 1 / General / Basic
Basic
Cluster ID: 0x0000, Enabled for Server
```

Here `< Endpoint 1 / General` is a hyperlink which seems weird. Would it make sense to make it look something as follows:
```
< Back
Endpoint 1 / General / Basic Cluster
Cluster ID: 0x0000, Enabled for Server
```
Where just back is a hyperlink which takes you back

**Comment by tecimovic** [comment]
I didn't like what we had before, @brdandu . But I don't like what we have now either.... :(

But I don't have a better idea at this point....

**Comment by brdandu** [comment]
> I didn't like what we had before, @brdandu . But I don't like what we have now either.... :(
> 
> But I don't have a better idea at this point....
> 
> Isn't there some standard practice how these should look? Doesn't every website in existence have some of these breadcrumbs? We should just follow what everyone else does....

Yeah I wish it looked cleaner. That blob looked off to me. If there are any better suggestions then I am open to it.
