### ISSUE TITLE
Custom XML file page looks very ugly

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#299]
![image](https://user-images.githubusercontent.com/7923190/141174711-59a6e9c8-900b-43d3-af90-575885a95ded.png)

When you expand these you just see a 4 line ugliness there. These should nicer.
We should not say "Required: True" or the "Package Type" stuff. That is meaningless to the user.

**Comment by SaharKargar** [comment]
Dear @tecimovic ,
Would you please give us more details about this issue?
Should we remove the mentioned data from UI and only show "Full File Path" and "Version"?
More feedback would be much appreciated.

**Comment by tecimovic** [comment]
Hold on with this a bit..... There is some serious lack of backend functionality that I need to work on to even get a good idea what this page needs.
So hold it off for now, and ping me in few days if I don't come back here and add more data.

**Comment by Mehradml** [comment]
I will put this back in the "Backlog" column for now.
Thanks @tecimovic.

**Comment by tecimovic** [comment]
The backend-work referred to above was all done by @jingteng25742

**Comment by jingteng25742** [comment]
The current "Add Custom ZCL" window switches perspectives from the original ZAP window unnecessarily. It takes up the whole window for no apparent reason and offer little functionality.
For the rework, this page should turn into a modal pop-up window, triggered by clicking the "ZCL Extensions..." button and displays the current entries. For the "ADD", we should use the "+" similar to the main page.

**Comment by wehale** [comment]
I don't see any change here?
