### ISSUE TITLE
Can't set attribute default back to empty

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#305]
1.) I pick an attribute, say "mains voltage" on Power Configuration cluster.
2.) Set a default to something, say 12.
3.) There is NO WAY, default can now be completely erased, so back to "empty" state.

I think we should have a little [x] in the corner of those text fields, with a tooltip "Reset to empty state" or something like that, which basically resets the default value back to the empty default state.

**Comment by bzbarsky-apple** [comment]
Or just allow the user to actually edit the field to set it to empty?  Especially for a string-typed attribute, where "empty string" is a perfectly good default value.
