### ISSUE TITLE
Display <description> in tooltips

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/zap#309]
if you look in ha.xml many elements contain \<description\> tags. The zap UI could be enhanced to display this text via tooltips when hovering over the various elements.

**Comment by paulr34** [comment]
The <description> tag has been added to ZclClusterView.vue. Tooltip was investigated but decided against.

**Comment by paulr34** [comment]
<img width="721" alt="Screen Shot 2022-04-20 at 10 44 43 AM" src="https://user-images.githubusercontent.com/64710345/164265882-26e949a7-9300-45e7-9cdc-7bb1aba090c7.png">
