### ISSUE TITLE
An attribute that has "reportable=true" in the XML is not made reportable automatically

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#318]
Attributes that have the "reportable" tag set operate like this:

1.) When you ENABLE the attribute on the "attribute" tab, they should immediatelly be made reportable, so if you go to "reporting" tab after enabling them, you should immediatelly see them enabled.

2.) If they are disabled later in the "reporting" tab, there should be a yellow triangle with a message "this attribute should be reportable" or something like that.

**Comment by tecimovic** [comment]
Note: this may or may not be a UI bug. It's possible that the bug happens in the back-end when the endpoint is created. We have to make sure that the database state itself is correct after creation of endpoint.
If the UI is simply reflecting the DB, and DB itself is wrong, then this is NOT a UI bug, but a backend bug.

**Comment by bzbarsky-apple** [comment]
In terms of the DB, if I examine the DB right after enabling the attribute on the endpoint the ATTRIBUTE table has IS_REPORTABLE true, but the ENDPOINT_TYPE_ATTRIBUTE has INCLUDED_REPORTABLE false for that attribute.  So the UI and the DB are in sync; what I don't know is which is supposed to be the source of truth here.  Obviously if I change things in the UI the DB gets updated.

**Comment by bzbarsky-apple** [comment]
Note that this bug is constantly corrupting the Matter .zap files: people add attributes, and forget to set them reportable, even though the spec requires them to be reportable.  What's the chance for progress on this?

**Comment by wehale** [comment]
This looks like it has been resolved in the consultant branch and can open a PR
