### ISSUE TITLE
Range checking in the UI should happen on load from ZAP file

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#331]
I just opened a ZAP file that had a default value of 200 set for an attribute with a max of 100.  The ZAP file was created before the "max" was added in the XML.

There was no "out of range" warning/error shown.  If I edit the default field and try to set it to 200, _then_ I get an error shown.

Error should be shown on invalid state no matter how we got into that state.

**Comment by wehale** [comment]
This looks resolved and can be merged
