### ISSUE TITLE
After loading custom XML file, things go wrong

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#335]
1.) Saving and reloading file looses data because the custom XML is not automatically reloaded.
2.) Generating from a separate process doesn't properly generate.

**Comment by jingteng25742** [comment]
Point 1 has been addressed. Merge pending.

**Comment by jingteng25742** [comment]
closing issue as point 1 is being addressed. 
point 2 should be address by https://github.com/project-chip/zap/issues/153
