### ISSUE TITLE
Help -> About innacessible from browser space

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#343]
In line with all the discussions about the menu:
   currently, "Help -> About" pops up a separate window, just like the "Preferences" did.

Can we move this into the browser space completely as well?

**Comment by babakzarrinbal** [comment]
added about in setting page of browser also
my suggestion : let it also be in menu ...

**Comment by tecimovic** [comment]
This was somewhat attempted, but the result is not nice.
About is now a "preference" page.

I don't want about to be a preference page. I want a menu item "About" that will show that picture as a floating frame in the center of the page.

**Comment by tecimovic** [comment]
Back to To-do column.

**Comment by SaharKargar** [comment]
@tecimovic do you want us to add an icon in the top-right corner of the main page, next to the gear icon for preferences page and when we click on it a modal would be shown with the content of about page?

**Comment by tecimovic** [comment]
Yeah, we can start with that. Ideally, I'd like to turn that whole area into a menu, so there would be "Help -> About". But a simple icon with (i) or something like that for "information" could be a good first step.
