### ISSUE TITLE
Toggling dark/light theme does nothing

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#344]
I toggle this:

![image](https://user-images.githubusercontent.com/7923190/145092226-f2d3920d-a642-4d79-bf56-8fa6a18f4056.png)

Nothing happens.

**Comment by tecimovic** [comment]
Note: if I go to the menu and do "View -> Dark Theme" and "View -> Light Theme" that does work.
It's just this toggle that does nothing...

**Comment by babakzarrinbal** [comment]
@tecimovic 
can't generate this issue on my local ...
everything works fine 
app setting page light/dark theme is working ...
electron menu light dark theme is working ...

**Comment by tecimovic** [comment]
Hm.....

**Comment by tecimovic** [comment]
I was stupid..... I didn't notice that this is TWO things. I was toggling that left/right toggle and assuming this is for dark and light.
You're right, the DARK/LIGHT button works.

@babakzarrinbal , can you please do the following:
 
 Make this look in two separate rows:
    1st row says: [ Toggle light/dark theme   [ * |  ]   ]
    2nd row says: [ Toggle development tools   [*| ] ]
    
So both rows have full text and both rows use the same kind of toggle that is used there for "Dev tools".

It makes no sense that "light/dark" is a silly weird button with bold fonts, but "Dev tools" is an actual toggle that you can drag left and right. So make the theme selector also being a toggle.

**Comment by babakzarrinbal** [comment]
@tecimovic 
did it as you asked 
will see it in pull request
