### ISSUE TITLE
Create cypress infrastructure to test UI and add it to the CI

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#350]
We have a lot of jest tests right now, but we don't have any UI-level tests.

The goal is:
  1.) Add at least one cypress test.
  2.) Add a new `npm run uitest` entry point that will execute the cypress test.
  3.) Show and teach everyone how to add more tests and maintain them in the future.

**Comment by tecimovic** [comment]
Clicked a wrong button.... Ignore these transitions....

**Comment by tecimovic** [comment]
Putting this back into the To-Do column until we resolve this.

**Comment by wehale** [comment]
The Cypress UI testing works and this can now be merged.
