### ISSUE TITLE
Retrieve lost sessions

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#351]
If zap crashes or weird things happen so you don't get to do File->Save, and you seem to have lost data, the data is not really lost, as the data is always behind the SESSION table in the database.

The functionality we need it as follows:
   1.) When zap starts up, query the SESSION table (taking USER into consideration), and find "lost" sessions.
   2.) Present a little dialog that shows all sessions and a checkbox next to them saying "Recover:"
   3.) Add another checkbox at the bottom that says: "Permanently delete unrecovered sessions".
   4.) Then you click OK and the following happens:
        a.) For each session that you checked "recover", a new window is opened with that session data.
        b.) If the "permanently delete" is checked, then physically delete all the data for those unrecovered sessions from the DB.

**Comment by jingteng25742** [comment]
@Mehradml 
I just pushed a new api, querySession.getUsersSessions(), that will provide a list of users and the corresponding sessions. Each session will have a dirty flag to indicate if saving was successfully or not.
