### ISSUE TITLE
Dependency package not found

### ISSUE THREAD

**Issue by hicklin** [project-chip/zap#361]
I am trying to get the tool running by following the instructions the the main `README.md` and `docs/instructions.md`. In the root directory of the project I have tried executing `npm ci` and `npm install`, following from the documentation files listed above. Both of these fail to install the dependency `https://nexus.tecnotree.com/repository/npm-public/listr2/-/listr2-3.13.5.tgz`. Failing with the error
```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://nexus.tecnotree.com/repository/npm-public/listr2/-/listr2-3.13.5.tgz failed, reason: getaddrinfo ENOTFOUND nexus.tecnotree.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

I am running node version `v16.13.1` and npm version `8.3.0`.

I have made sure that I am not behind a proxy and ran the following npm configuration commands

```
npm config rm proxy
npm config rm https-proxy
npm config --global rm proxy
npm config --global rm https-proxy
```

**Comment by tecimovic** [comment]
This was fixed. There was some "tecnotree" nonsense that weasled it's way into the package.json at some point.
