### ISSUE TITLE
For Matter, reportability is entirely spec-defined, not user-controlled

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#368]
For Matter, reportability should just come from the XML, not from a UI setting.  No opinion on whether the UI setting should be ignored or disabled, but it should not be possible to set an attribute non-reportable that the Matter spec requires to be reportable.

This is related to https://github.com/project-chip/zap/issues/318 but not identical.

It's possible that this could be addressed by exposing the "default" reportability of the attribute in queries, in addition to whatever was set in the UI, and changing matter templates to use that value.

**Comment by tecimovic** [comment]
Should be resolved in https://github.com/project-chip/zap/pull/375

**Comment by bzbarsky-apple** [comment]
Not fixed until PR is merged....
