### ISSUE TITLE
Expand matrix of supported environment

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#369]
- make sure zap works on M1 based Macs
- make sure zap works with node 16+ and latest npms
- make sure zap works equally well on Windows, Macs and Linuxes

Generally:
   we keep getting users who are using some hardware that is outside of our operational matrix and people run into trouble. We should expand that by having more diverse set of hardware and also by doing CI on something else than just a Linux box.

**Comment by wehale** [comment]
@Mehradml how was this tested? I don't have a way of replicating this test because I don't have all the environments listed.
