### ISSUE TITLE
Device Type value does not change after manual edit

### ISSUE THREAD

**Issue by rochaferraz** [project-chip/zap#373]
When trying to edit an endpoint's device type (Endpoint > EDIT > Device), ZAP GUI will only accept a manual entry of device type if the user types the value and then hits <tab>. If the user instead types a manual value and selects another field or closes the window it will not save the edited input value.

Possibly related to #305

**Comment by brdandu** [comment]
https://github.com/project-chip/zap/issues/305 is resolved. @rochaferraz is this still an issue or can we close this?

**Comment by Phenomenan** [comment]
@rochaferraz we tested the issue and it's working fine. Is this still an issue or can we close it?
