### ISSUE TITLE
"Profile ID" is meaningless for Matter 

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#394]
See https://github.com/project-chip/connectedhomeip/issues/5637 but this is really a ZAP UI issue: when configuring a Matter app, "Profile ID" makes no sense.

**Comment by wehale** [comment]
It isn't just teh Profile Id, there are many things that are different in the UI for Matter as opposed to Zigbee, this needs to be configurable through key/value pairs in the SDK.

**Comment by tecimovic** [comment]
I've added a mechanism for this: if you add a section "uiOptions" into zcl.json, this will propagate through REST API via `httpGetUiOptions` REST call in `user-data.js`. (At the time of writing this code is still in a PR, not yet on master).

**Comment by tecimovic** [comment]
See PR https://github.com/project-chip/zap/pull/414
It contains the code that gives you the `httpGetUiOptions` REST API.

**Comment by Amirreza-Ghasemkhani** [comment]
https://github.com/project-chip/zap/pull/653

**Comment by paulr34** [comment]
feel free to close this one out when you close out the other one @tbrkollar
