### ISSUE TITLE
In dark theme, endpoint scrollbar is too glaring

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#398]
![image](https://user-images.githubusercontent.com/7923190/151855015-594e1638-36cd-449a-a8fc-a505b103a715.png)

**Comment by tecimovic** [comment]
The scrollbar for the endpoints is very bright and attracts a lot of attention. On the other hand, the scroll bar on the right-side for the clusters table is much less intrusive.

They should look the same.

**Comment by tecimovic** [comment]
The scrollbar is also covering the blue boundary around the selected endpoint.

**Comment by wehale** [comment]
REviewing this and I still see the same thing with the scroll bar, it is as though it is from the light theme.

**Comment by wehale** [comment]
Both Timotej and myself are not able to see this as corrected. I'm moving this back to To Do, something different needs to be done here because we both still see the glaring white scroll bar on Linux and Mac. Thanks
