### ISSUE TITLE
Need a way to mark structs fabric-scoped and events fabric-sensitive in the XML

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#411]
Right now we guess that structs are fabric-scoped based on their fields.

We should reverse that: the struct declaration should explicitly say whether the struct is fabric-scoped or not, and if it is it automatically gets the global FabricIndex field with the well-known global id, etc.

**Comment by bzbarsky-apple** [comment]
> We already have isFabricScoped on the struct items

I don't think we do.  We have isFabricSensitive, which is not the same thing.

> Do you still want an explicit "isFabricScoped" on the struct even if it already has a field with an "isFabricScoped" property set?

A struct with a fabric-sensitive field must be fabric-scoped.

But a struct can be fabric-scoped without containing any fabric-sensitive fields.

> Is a state where struct DOES NOT have an "isFabricScoped" set, but at least ONE of the field does, valid?

Assuming you mean isFabricSensitive for the field, no.

> Is a state where struct DOES have an "isFabricScoped" set, but NONE of the field does, valid?

Yes.

> Would those apply here as well?

Good catch.  We need something similar for events, but for events I think we will want to do isFabricSensitive, based on the semantics of the behavior and where I expect the spec terminology to land.

We will not need this for bitmaps and enums.

**Comment by bzbarsky-apple** [comment]
I believe this is done now....

**Comment by brdandu** [comment]
Closing this.
