### ISSUE TITLE
Remove the exception prevention blocks.

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#415]
Remove these blocks from Cypress tests:
```
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})
```

**Comment by tecimovic** [comment]
Note: if there are exceptions in the JS layers that prevent any of the test to run, we should fix them.

I would do this:
   1.) Turn them off for ALL the tests.
   2.) See what breaks.
   3.) Add this back to just the tests that break.
   4.) Start fixing them one-by-one.
   
I would really like to get to the state where there are NO exceptions, and then if some new change in the future introduces exceptions, the tests actually fail.

**Comment by SaharKargar** [comment]
It would be better if we could have a new issue for resolving the exceptions and we will work on them.

**Comment by Mehradml** [comment]
This task would be continued in the following issue
https://github.com/project-chip/zap/issues/426
