### ISSUE TITLE
ZCL packages preference page

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#422]
![image](https://user-images.githubusercontent.com/7923190/154771304-7fccb27d-0e3c-46ea-a242-619da8e81416.png)

Make this page do something useful, please.

I would ideally like to see a table of all the packages in the database, essetially the "package" table.
We start with that, then we see what else we can add.

**Comment by wehale** [comment]
Minor nit, the "Records Per page" dropdown at the bottom of the page doesn't appear to do anything
