### ISSUE TITLE
Generation preference page

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#423]
![image](https://user-images.githubusercontent.com/7923190/154771397-87628e3b-638f-4f0d-8d45-9214bd5f1578.png)

This page should show:
  1.) Templates grouped by the template packages.
  2.) Ideally, I'd like to be able to view the content of templates.

**Comment by tecimovic** [comment]
When I said "content", I did not mean the actual text content of the files. I said that a wrong way...
For the "content", I mostly meant the path and other metadata that is in the PACKAGE table. We never need to show the actual text content of the files.
I'll reopen the bug, so you can take that out. We should not be reading the actual content and sending it to the frontend.

**Comment by tecimovic** [comment]
If you can take out that logic that does the file-read and sends all that to the front-end, that would be good.

**Comment by wehale** [comment]
When I go to generation preferences and back the preview pane is open. Also the "records per page" drop down doesn't do anything And Timotej said he wanted to see the contents of the templates but I can't see how to view that here. This isn't really a preference page it is just a list of all the generation templates, I don't really see how useful this is.
