### ISSUE TITLE
Change the versioning scheme to avoid constant rebasing conflicts in package.json

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#488]
We have this line in package.json:

  "version": "2022.4.26",

It is the main cause of all kind of rebasing conflicts.

We need to change this, to be calculated on the fly, since it's really just a date of the last commit.

**Comment by tecimovic** [comment]
The current idea:
  1.) The commited version inside package.json is set to something like "0.99.99". So a bogus version. We don't change it.
  2.) Whenever we build zap or execute zap, the script temporarily changes this "version" to a valid date version.
  3.) Husky pre-commit job, always takes care that this is reset back to 0.99.99, so we don't commit a valid version by mistake.

So in essence this would just temporarily inject a "real" version, while not committing it. Could that work? Any other ideas?

It seems a bit odd, but at this point I don't have a better idea! Anyone?

**Comment by jingteng25742** [comment]
What is the downside of not changing the "version" field or even updating the field behind-the scene at all? 

Currently, we are sidestepping the "version" /  "Semantic Versioning" with our own mix of feature level / hash / date.
I don't believe that field is used to any functional capacity. Even in the "About" page, the value can be extracted via "date" field. 

For downsides, I think auto-update might not work but that's not leverage currently anyways.
