### ISSUE TITLE
Fix the mechanism how Zap menu is or is not shown on standalone vs IDE

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#506]
If you run a release `silabs-rel` branch, then you don't see the menu at all when you start up standalone.
If you run a `silabs` branch you do.

We need to fix this.

There should be a functionality in ZAP that turns menu on or off based on a request from the renderer.

**Comment by jingteng25742** [comment]
@tecimovic what do you mean by "menu"? 
If you are referring to the "ZCL / Generate / Preview" menu? 
If so, hiding it on silabs-rel is intentional since it was a bar for debugging.

**Comment by jingteng25742** [comment]
Closing issue since this is more of an intended behavior.
