### ISSUE TITLE
ZAP attribute editing UI broken in some cases

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#510]
Steps to reproduce:

1. Check out git@github.com:project-chip/connectedhomeip.git
2. `cd connectehomeip/third_party/zap/repo`
3. `git checkout master`
4. `git pull origin master`
5. `git checkout c684c73806490efae688b1c83913304c6aeb6cd6` (master as of right now)
6. `cd ../../..`
7. `git add third_party/zap/repo`
8. `./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap`
9. Select "Endpoint - 1" on the left-hand side.
10. Type "Test" in the cluster filter field.
11. Select the gear icon ("Configure") for "Test Cluster"

Expected results: Can edit attribute stuff

Actual results: No attributes are listed, ZAP UI freezes.

This is a recent-ish regression.  Things work correctly on ZAP revision e9277b989f1d128bc881e88ecbf7a3353c841c39 (which is the current Matter ZAP pull).

@tecimovic

**Comment by tecimovic** [comment]
@Mehradml : please take a look at this. If it is something that is not related to your work, but something we did (which is also possible), please let me know.
