### ISSUE TITLE
npm ci and npm install errors

### ISSUE THREAD

**Issue by Leo2442926161** [project-chip/zap#521]
I am setting zap environment, it shows errors when I run npm ci, is there any requiresments? many thanks.

`npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/leo/matter/zap/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/leo/matter/zap/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/leo/matter/zap/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 5.4.0-110-generic
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/home/leo/matter/zap/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/leo/matter/zap/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v16.15.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! node-pre-gyp ERR! not ok
`

**Comment by tecimovic** [comment]
There is faq doc: https://github.com/project-chip/zap/blob/master/docs/faq.md

It has two sections:
   How to make this work on Mac/Linux?
And:
   How to make this work on Windows?

There are some dependencies that might need to be installed locally, for the `npm` to work correctly.
Did you do those things?

Also:
   what does your `node --version` say and what does your `npm --version` say?

**Comment by tecimovic** [comment]
Also note: I've occasionally seen errors from `npm` which were just "warnings", since npm then found another way to do the same thing.
After you get these errors, can you run `npm run self-check` ?

**Comment by Leo2442926161** [comment]
Hi Tecimovic, thanks a lot for your help.

I tried couple of methonds to tackle "node-gyp-build: Permission denied" error, but it still not works.


`leo@leo-virtual-machine:~/matter/zap$ node -v
v16.15.0
leo@leo-virtual-machine:~/matter/zap$ npm -v
8.10.0`

`leo@leo-virtual-machine:~/matter/zap$ npm run self-check

> zap@2022.5.18 self-check
> node src-script/zap-start.js selfCheck -g ./test/gen-template/zigbee/gen-templates.json

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'cross-spawn'
Require stack:
- /home/leo/matter/zap/src-script/script-util.js
- /home/leo/matter/zap/src-script/zap-start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/leo/matter/zap/src-script/script-util.js:17:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/leo/matter/zap/src-script/script-util.js',
    '/home/leo/matter/zap/src-script/zap-start.js'
  ]
}`


`npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 126
npm ERR! path /home/leo/matter/zap/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-buil
[npm install error.txt](https://github.com/project-chip/zap/files/8751797/npm.install.error.txt)
d
npm ERR! sh: 1: node-gyp-build: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-23T05_37_17_564Z-debug-0.log`

**Comment by Leo2442926161** [comment]
> Also note: I've occasionally seen errors from `npm` which were just "warnings", since npm then found another way to do the same thing. After you get these errors, can you run `npm run self-check` ?

it shows connetcion timeout when I remove sudo permisstion

```
npm install

...

npm ERR! code 1
npm ERR! path /home/leo/matter/zap/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! RequestError: connect ETIMEDOUT 192.30.253.112:443
npm ERR!     at ClientRequest.<anonymous> (/home/leo/matter/zap/node_modules/got/source/request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:642:26)
npm ERR!     at ClientRequest.emit (node:events:539:35)
npm ERR!     at ClientRequest.origin.emit (/home/leo/matter/zap/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:454:9)
npm ERR!     at TLSSocket.emit (node:events:527:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leo/.npm/_logs/2022-05-23T06_06_30_725Z-debug-0.log
```

**Comment by Leo2442926161** [comment]
Hi Tecimovic,

I tried many times but still encountering the problem below, could you help me out, thanks very much.

```
npm ERR! code 1
npm ERR! path /home/leo/matter/zap/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! RequestError: connect ETIMEDOUT 192.30.253.112:443
npm ERR!     at ClientRequest.<anonymous> (/home/leo/matter/zap/node_modules/got/source/request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:642:26)
npm ERR!     at ClientRequest.emit (node:events:539:35)
npm ERR!     at ClientRequest.origin.emit (/home/leo/matter/zap/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:454:9)
npm ERR!     at TLSSocket.emit (node:events:527:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leo/.npm/_logs/2022-05-25T08_03_15_241Z-debug-0.log

```

**Comment by jingteng25742** [comment]
@Leo2442926161 

`npm install` failing to finish is preventing you from building ZAP successfully.
Is your computer behind a proxy?
If you do not need to use ZAP from source, you can download ZAP binaries from https://github.com/project-chip/zap/actions/runs/3023996990

**Comment by brdandu** [comment]
@Leo2442926161 following up on @jingteng25742 comment above. Is this still an issue for you?

**Comment by paulr34** [comment]
I could not reproduce this with the latest ZAP
