### ISSUE TITLE
ZAP Endpoint display issue

### ISSUE THREAD

**Issue by jingteng25742** [project-chip/zap#527]
![image](https://user-images.githubusercontent.com/61332088/170096927-466e51df-f9fc-4bf7-8df8-b69b533fde99.png)

1) Within above pictures, the values of "Enabled Clusters" / etc should be left aligned, similar to Version.
2) Each Endpoint entry (Endpoint - 1, Endpoint - 2) should be able to be expanded individually. Previously, the user is able to see all endpoint attribute fields. This behavior needs to return. Behavior similar to https://quasar.dev/vue-components/expansion-item

**Comment by wehale** [comment]
I'm not able to validate that this has been resolved. To me it appears that the values for Enabled Clusters, Enabled Attributes, and Enabled reporting are all right aligned still.
