### ISSUE TITLE
Feature Request: Duplicate endpoint configuration

### ISSUE THREAD

**Issue by ldoering** [project-chip/zap#528]
When working with a device containing multiple endpoints with the same functionality on multiple endpoints, it would be much easier if the configuration can be done once and duplicated for all desired endpoints. The current approach is to configure all endpoints manually, which is quite time consuming.

**Comment by Amirreza-Ghasemkhani** [comment]
https://github.com/project-chip/zap/pull/695

**Comment by ldoering** [comment]
When testing this feature, I noticed that the enabled commands seem to be ignored and had to enabled manually. 
Is this a bug or a feature?
