### ISSUE TITLE
Empty new configuration has "dirty" flag on

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#541]
1.) Run `npm run zap`.
2.) See the new window have a `dirty` flag.

A new window should NOT be dirty, until you actually start doing something. Only when you do something to it that makes it actually have some data, will it be dirty.

The problem is then, that if the first think you do, is do "File -> Open" and try to open a file, that will spawn a new window.

To the second part of this bug is ensure that the following flow works:

1.) Run `npm raun zap`, see the "New configuration" window.
2.) Choose "File -> Open" and open an existing zap file.
3.) Make sure that this new zap file realizes that the current window is blank, and the current window will thus be reused.

If the window we have is dirty or already has a file opened, it should not be reused, but if it's just a "new configuration" window without user doing anything to it, so it's neither dirty, nor it has any data, then it should be reused.

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/pull/633 approved by Timotej
