### ISSUE TITLE
Allow global attributes to have forced storage option

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#543]
We have code in `src-electron/zcl/zcl-loader-silabs.js` that sets storage policy like so:
```
      let storagePolicy = dbEnum.storagePolicy.any
      if (context.listsUseAttributeAccessInterface && attribute.$.entryType) {
        storagePolicy = dbEnum.storagePolicy.attributeAccessInterface
      } else if (
        context.attributeAccessInterfaceAttributes &&
        context.attributeAccessInterfaceAttributes[cluster.name] &&
        context.attributeAccessInterfaceAttributes[cluster.name].includes(name)
      ) {
        storagePolicy = dbEnum.storagePolicy.attributeAccessInterface
      }
```
but that code does not run for global attributes, as far as I can tell.  Then later when we try to use the storage policy in `src-electron/db/query-impexp.js` in `importAttributeForEndpointType` I am not sure _that_ code runs for global attributes either.

So in practice the storage policy bits don't work for global attributes.

**Comment by tecimovic** [comment]
There is currently a mechanism that forced storage option to be external for certain attributes, via this block inside the zcl.json file:
```
  "listsUseAttributeAccessInterface": true,
  "attributeAccessInterfaceAttributes": {
    "Access Control": [
      "ClusterRevision",
      "SubjectsPerAccessControlEntry",
      "TargetsPerAccessControlEntry",
      "AccessControlEntriesPerFabric"
    ],
    "AdministratorCommissioning": [
      "WindowStatus",
      "AdminFabricIndex",
      "AdminVendorId"
    ],
    "Basic": [
      "DataModelRevision",
      "VendorName",
      "VendorID",
      "ProductName",
      "ProductID",
      "Location",
      "HardwareVersion",
    ...
```

If you put a global attribute into this block, however, this doesn't work per cluster. There isn't also any place in the database to put this data per-cluster for a global attribute. We should add this to GLOBAL_ATTRIBUTE_DEFAULT (possibly renaming the table to GLOBAL_ATTRIBUTE_PER_CLUSTER_POLICY).

**Comment by tecimovic** [comment]
So what I plan to do, and @bzbarsky-apple , please review:

1.) Rename GLOBAL_ATTRIBUTE_DEFAULT to GLOBAL_ATTRIBUTE_CLUSTER_POLICY.
2.) Add in there a column STORAGE_POLICY.
3.) Concoct a mechanism that will allow for that thing in zcl.json to also refer to global attributes, same way as it refers to non-global ones.
4.) Properly populate this table with per-cluster STORAGE_POLICY.
5.) Fix the things that read this data to make use of this (mostly the thing that creates endpoints, which currently already takes the defaults from this table, but now it should also take storage option from it).

**Comment by bzbarsky-apple** [comment]
@tecimovic That plan sounds good, I think, if I understand how these things fit together.

> Possibly: why is this called "attributeAccessInterface"?

On the Matter side: because that's why we're forcing these things to be external-storage, and because that's what the storage-policy enup in ZAP got named.  But I don't have any particular attachment to the naming here.

**Comment by paulr34** [comment]
sorry @bzbarsky-apple copying my comment here https://github.com/project-chip/zap/issues/1110 so @tecimovic sees it

see: https://github.com/project-chip/zap/issues/1110

@bzbarsky-apple I think I figured it out. The global attributes are labeled as "attribute"within general.xml and they should actually be labeled as "globalAttribute".

Maybe there is a better solution but at the moment the code treats global attributes like non global attributes and it doesn't work because the cluster is undefined. The only way to match a referenced cluster is to run a "forcedExternalCheck()" or something like that on each cluster which cross references globals in the globalAttribute list generated by the XML tag and our list of clusters/attributes pairs that are supposed to be external storage.

**Comment by paulr34** [comment]
completed https://github.com/project-chip/zap/pull/1142 will make new issues for follow up work
