### ISSUE TITLE
Show to user whether Zigbee or Matter is used.

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#556]
![image](https://user-images.githubusercontent.com/7923190/173588357-8f555a68-0ff8-4b85-a1e7-96186babacf4.png)

Show which specific toplevel zcl-properties is used for this configuratio.

You can show a string:
   "Cluster configurator: Zigbee"
   or
     "Cluster configurator: Matter"
 
 or something like that.

The string to use, is in the database, in the VERSION field of the PACKAGE table. So depending on which toplevel package is chosen by the users, the UI shows what is being used.

**Comment by jingteng25742** [comment]
For the text, perhaps we can standardize / follow the format as to the rest of the bar ( .e.g. ZCL GLOBAL OPTOINS / ZCL Extensions)
.e.g. "#logo [Zigbee | Matter] Cluster Configurator"
#logo being either the Zigbee or Matter official logo.
