### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by ble0** [project-chip/zap#586]
In the latest master, I'm having issues when doing `npm run zap` on Mac M1 and I managed to install prerequisites without running into issues:
node version: v14.17.3
npm version: 6.14.13
> 🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
> 🔍 Git commit: 20a5bb72c536fddde419716501b32cb56a45c51b from Thu Jul 07 2022 10:17:43 GMT+0800 (Singapore Standard Time)
> 🔍 Version output:   "version": "2022.7.7",
> 🔍 Current src hash: MIhOTMPVd+31Oq/0S7UrViKfJYE=
> 🔍 Current src-shared hash: p5+1unpLVPLVAp5dpKJi/RTdYL8=
> 🔍 Previous src hash: MIhOTMPVd+31Oq/0S7UrViKfJYE=
> 🔍 Previous src-shared hash: p5+1unpLVPLVAp5dpKJi/RTdYL8=
> 👍 There were no changes to front-end code, so we don't have to rebuild the SPA.
> 🚀 Executing: npx tsc --build ./tsconfig.json
> 🚀 Executing: npx copyfiles -V ./src-electron/**/*.sql ./dist/
> unglobed path: ./src-electron/db/zap-schema.sql
> copy from: ./src-electron/db/zap-schema.sql
> copy to: dist/src-electron/db/zap-schema.sql
> 🚀 Executing: npx electron /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/ui/main-ui.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json
> ⇝ App threw an error during load
> ⇝ Error: Cannot find module '/Users/mark/esp/nami/test/matter/zap_master/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
> Require stack:
> - /Users/mark/esp/nami/test/matter/zap_master/node_modules/sqlite3/lib/sqlite3-binding.js
> - /Users/mark/esp/nami/test/matter/zap_master/node_modules/sqlite3/lib/sqlite3.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/db/db-api.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/db/query-package.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/util/util.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/ui/ui-util.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/ui/menu.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/ui/window.js
> - /Users/mark/esp/nami/test/matter/zap_master/dist/src-electron/ui/main-ui.js
> - /Users/mark/esp/nami/test/matter/zap_master/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
> - 
>     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
>     at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
>     at Module._load (node:internal/modules/cjs/loader:785:27)
>     at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
>     at Module.require (node:internal/modules/cjs/loader:1012:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/mark/esp/nami/test/matter/zap_master/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
>     at Module._compile (node:internal/modules/cjs/loader:1116:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
>     at Module.load (node:internal/modules/cjs/loader:988:32)

<img width="263" alt="Screenshot 2022-07-07 at 18 37 20" src="https://user-images.githubusercontent.com/19359534/177754550-f02017cc-7d47-49d1-9d80-b1caf32be079.png">
<img width="266" alt="Screenshot 2022-07-07 at 18 38 41" src="https://user-images.githubusercontent.com/19359534/177754916-260aa097-1d03-456a-893d-ac33512f8891.png">
<img width="269" alt="Screenshot 2022-07-07 at 18 39 00" src="https://user-images.githubusercontent.com/19359534/177755040-2ac0530d-106f-43d6-a435-122e21b28995.png">
<img width="265" alt="Screenshot 2022-07-07 at 18 39 07" src="https://user-images.githubusercontent.com/19359534/177755062-412fc8a7-fc81-4f10-ac7b-adcb7b10a733.png">

**Comment by jingteng25742** [comment]
@ble0 
This might be an issue of npm/electron having mismatched binaries between Intel / Apple images.
Can you check your 'Activity Monitor' for the "Kind" field for "npm" / "Electron" processes? 
If there's a mismatch, installing the arm64 version of node will resolve the issue.

![image](https://user-images.githubusercontent.com/61332088/177857869-f271103c-e8c4-4a57-9ea8-53d39969156e.png)

**Comment by ble0** [comment]
hi I managed to re-install the npm via homebrew and it seems it installed the correct version. I can now run the zap utility
