### ISSUE TITLE
Running generate.py the in docker container fails

### ISSUE THREAD

**Issue by kvaellning** [project-chip/zap#601]
I am using a docker container running the Ubuntu 20.04 image.
For the build process, I want to rely on the auto-generation of the necessary files based on a given zap-file.

Trying to start the `script/zap/generate.py` does not work, since the `zap-generate.js` needs `yargs`. Trying to install it I get multiple errors, mostly related to `canvas` etc. From this, I would say the problem originates in missing GUI stuff in the docker.
Tbh, I have no idea about node, npm and whatsoever; so I feel absolutely overwhelmed.

Shouldn't there be a way generate the files without the need for any GUI related stuff?`Or am I completely on the wrong path?

**Comment by tecimovic** [comment]
Did you run `npm install` or `npm ci` inside the third_party/zap/repo directory?

Before zap is usable, you need to do that.
After you run either `npm install` or `npm ci`, you can try: `npm run self-check` which will run simple check telling you that everything is ok.

We've seen occasional problem with canvas. Look at the faq.md (linked from README.md) which lists some helpful data points. There are scripts: src-script/install-packages-[osx/fedora/ubuntu] that bring in few extra packages.

The UI is not required just for regeneration, but the npm ci will install everything that is needed for the user-interface as well, so just to set things up, you do need to install all the UI libraries and such.

**Comment by kvaellning** [comment]
I have the container currently running and playing around, simply using `npm install` will result in the following error message:
`
> zap@0.0.0 postinstall
> electron-builder install-app-deps && husky install && npm rebuild canvas --update-binary && npm run version-stamp

  • electron-builder  version=22.14.13
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=bufferutil@4.0.6, canvas@2.9.1, sqlite3@5.0.8, utf-8-validate@5.0.9 platform=linux arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /usr/matter/third_party/zap/repo/node_modules/canvas
    npm ERR! command failed
    npm ERR! command sh -c node-pre-gyp install --fallback-to-build
    npm ERR! make: Entering directory '/usr/matter/third_party/zap/repo/node_modules/canvas/build'
    npm ERR!   SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
    npm ERR! make: Leaving directory '/usr/matter/third_party/zap/repo/node_modules/canvas/build'
    npm ERR! Failed to execute '/root/.nvm/versions/node/v16.15.0/bin/node /root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/matter/third_party/zap/repo/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/matter/third_party/zap/repo/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v17.4' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
    npm ERR! node-pre-gyp info using node@16.15.0 | linux | x64
    npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-electron-v17.4-linux-glibc-x64.tar.gz
    npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-electron-v17.4-linux-glibc-x64.tar.gz 
    npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and electron@17.4.7 (electron-v17.4 ABI, glibc) (falling back to source compile with node-gyp) 
    npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-electron-v17.4-linux-glibc-x64.tar.gz 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.15.0 | linux | x64
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.15.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
    npm ERR! gyp http GET https://electronjs.org/headers/v17.4.7/node-v17.4.7-headers.tar.gz
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v17.4.7/node-v17.4.7-headers.tar.gz
    npm ERR! gyp http GET https://electronjs.org/headers/v17.4.7/SHASUMS256.txt
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v17.4.7/SHASUMS256.txt
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/usr/matter/third_party/zap/repo/node_modules/canvas/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/root/.electron-gyp/17.4.7/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.electron-gyp/17.4.7',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.electron-gyp/17.4.7/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/matter/third_party/zap/repo/node_modules/canvas',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.15.0 | linux | x64
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! arm-none-eabi-c++: error: unrecognized command-line option '-pthread'
    npm ERR! arm-none-eabi-c++: error: unrecognized command-line option '-rdynamic'
    npm ERR! arm-none-eabi-c++: error: unrecognized command-line option '-m64'
    npm ERR! make: *** [canvas-postbuild.target.mk:22: Release/obj.target/canvas-postbuild.node] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Linux 5.15.13-051513-generic
    npm ERR! gyp ERR! command "/root/.nvm/versions/node/v16.15.0/bin/node" "/root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/matter/third_party/zap/repo/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/matter/third_party/zap/repo/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v17.4"
    npm ERR! gyp ERR! cwd /usr/matter/third_party/zap/repo/node_modules/canvas
    npm ERR! gyp ERR! node -v v16.15.0
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok 
    npm ERR! node-pre-gyp ERR! build error 
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v16.15.0/bin/node /root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/matter/third_party/zap/repo/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/matter/third_party/zap/repo/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v17.4' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/matter/third_party/zap/repo/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
    npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    npm ERR! node-pre-gyp ERR! System Linux 5.15.13-051513-generic
    npm ERR! node-pre-gyp ERR! command "/root/.nvm/versions/node/v16.15.0/bin/node" "/usr/matter/third_party/zap/repo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    npm ERR! node-pre-gyp ERR! cwd /usr/matter/third_party/zap/repo/node_modules/canvas
    npm ERR! node-pre-gyp ERR! node -v v16.15.0
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
    npm ERR! node-pre-gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2022-07-14T12_23_59_272Z-debug-0.log
    
                    command=/root/.nvm/versions/node/v16.15.0/bin/node /root/.nvm/versions/node/v16.15.0/lib/node_modules/npm/bin/npm-cli.js rebuild bufferutil@4.0.6 canvas@2.9.1 sqlite3@5.0.8 utf-8-validate@5.0.9
                    workingDir=
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.14.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.14.0
npm notice Run npm install -g npm@8.14.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /usr/matter/third_party/zap/repo
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps && husky install && npm rebuild canvas --update-binary && npm run version-stamp

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-14T12_21_44_438Z-debug-0.log
`
running `npm run self-check` then tells me everything works fine - is this intended behavior?

**Comment by kvaellning** [comment]
Running in the gitlab pipeline, I'll get the same npm error, but now `npm run self-check` also fails with:
```shell
$ npm run self-check
> zap@2022.4.29 self-check
> node src-script/zap-start.js selfCheck -g ./test/gen-template/zigbee/gen-templates.json
node:internal/modules/cjs/loader:949
  throw err;
  ^
Error: Cannot find module 'cross-spawn'
Require stack:
- /builds/siegenia/p194_window_sensor/firmware/application_firmware/window-sensor/modules/lib/matter/third_party/zap/repo/src-script/script-util.js
- /builds/siegenia/p194_window_sensor/firmware/application_firmware/window-sensor/modules/lib/matter/third_party/zap/repo/src-script/zap-start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/builds/siegenia/p194_window_sensor/firmware/application_firmware/window-sensor/modules/lib/matter/third_party/zap/repo/src-script/script-util.js:17:19)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/builds/siegenia/p194_window_sensor/firmware/application_firmware/window-sensor/modules/lib/matter/third_party/zap/repo/src-script/script-util.js',
    '/builds/siegenia/p194_window_sensor/firmware/application_firmware/window-sensor/modules/lib/matter/third_party/zap/repo/src-script/zap-start.js'
  ]
}
Node.js v18.4.0
```

**Comment by brdandu** [comment]
Wondering if you need and `xvfb-run` wrapper

**Comment by jingteng25742** [comment]
@kvaellning 
"Error: Cannot find module 'cross-spawn'" implies "npm install" was not successful, which is echo'ed by your post about the canvas failures. 

Did you run "zap/src-script/install-packages-ubuntu" to make sure you have all the required linux packages for ZAP?
