### ISSUE TITLE
Unmuddle session package linking

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#615]
The root of the problem seems this:
   1.) import-json, imports stuff, and gets the package IDs, but it does NOT enter package IDs into the database.
   2.) It DOES however enter the packageId for the custom XML files.
   3.) then only later at some point, the initializeSession() function links the rest of the package IDs.

This is somewhat messy. It needs to be cleaned up.

**Comment by paulr34** [comment]
closing since a duplicate issue was created with more info https://github.com/project-chip/zap/issues/850
