### ISSUE TITLE
Show Dialog for Edit Endpoint

### ISSUE THREAD

**Issue by Amirreza-Ghasemkhani** [project-chip/zap#637]
When an endpoint is created and a device is chosen, you will see the device summary on the endpoint card .that summary includes the number of enabled attributes, etc.. 
the issue: everything works fine when attempting to edit the device to a new one. but when the previous device gets chosen again,, the summary is not updated.

**Comment by jingteng25742** [comment]
When changing an Endpoint to a new Device Type, a prompt should appear to ask the user if the existing configuration (cluster/attribute/etc) should be retained or not.
Prompt can be: Would you like to keep the configurations from previous Device Type?

**Comment by paulr34** [comment]
this is fixed with the latest

I can create an endpoint and edit it with the same device and the summary is updated. Please reopen if there is disagreement.
