### ISSUE TITLE
ZAP tool usage problem, help needed.

### ISSUE THREAD

**Issue by googlehim** [project-chip/zap#704]
npm run pack:linux
npm run pack:win
npm run zap-devserver
these commands run successfully, but I can't change "ZCL EXTENSIONS" in web browser or standalone linux or windows version in UI, and plus there is no file menu on top of web UI page, so I can't open/save a *.zap file . I am trying to edit and  save a conectedhomeip app.zap file.  For your information, if i run ./connectedhomeip/scripts/tool/zap/run_zaptool.sh,  ZAP tools UI can change "ZCL EXTENSIONS" files, can you hlep? what am i missing, thank you.

![image](https://user-images.githubusercontent.com/9864527/188817112-98d6ae3f-80bb-4b88-a1db-b1b750013fb6.png)
"Cluster Configurator: ZigbeePro test data" how to change this to "Cluster Configurator: Matter test data"
"Add Custom ZCL" How can I add connectedhomeip/src/app/zap-temlates/zcl/zcl.json and connectedhomeip/src/app/zap-templates/app-templates.json for matter project?

**Comment by googlehim** [comment]
I figured it out, should executed from command line with options to open UI:
./zap -z  PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap

but
./zap server  -z  PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap'tt
doesn't work this way.

**Comment by brdandu** [comment]
> I figured it out, should executed from command line with options to open UI: ./zap -z PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap
> 
> but ./zap server -z PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap'tt doesn't work this way.

May I know what you are trying to do as an end goal?
Does `./zap -z PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap` solve your issue?

**Comment by googlehim** [comment]
> > I figured it out, should executed from command line with options to open UI: ./zap -z PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap
> > but ./zap server -z PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap'tt doesn't work this way.
> 
> May I know what you are trying to do as an end goal? Does `./zap -z PATH/zcl.json -g PATH/app-templates.json -i PATH/my.zap` solve your issue?

I want edit zap file and generate code for matter project, my first try is compile/pack standalong windows/linux version ZAP tools, double click zap application and do other things  under UI circumstance.  Like open/save zap file, change zcl.json or app-template.json, I thought all these operations can be done from UI, but in fact can't.

**Comment by googlehim** [comment]
![image](https://user-images.githubusercontent.com/9864527/189413982-a1d7fa10-6ac7-4c30-b3ad-312efc72818a.png)
![image](https://user-images.githubusercontent.com/9864527/189414169-6ae9dc70-28ea-41bd-bfbe-d35c4adcebf2.png)
Cluster Configurator: **ZigbeePro test data**
why still "ZigbeePro test data", I expected "Matter SDK ZCL data"
