### ISSUE TITLE
count of enabled attribute has a problem

### ISSUE THREAD

**Issue by Amirreza-Ghasemkhani** [project-chip/zap#723]
when you create an endpoint attribute count is okay but after refreshing the page it will change and it's not correct.

**Comment by Amirreza-Ghasemkhani** [comment]
after disabling all the clusters attribute count show wrong number also after enabling cluster and disabling that attribute count show wrong number.

**Comment by brdandu** [comment]
Need to get rid of counts. Moving this to do.
