### ISSUE TITLE
Endpoint Summary Issue

### ISSUE THREAD

**Issue by Amirreza-Ghasemkhani** [project-chip/zap#725]
After deleting an endpoint all of the endpoints summary will show wrong counts

**Comment by Amirreza-Ghasemkhani** [comment]
count of endpoint's clusters and attributes need to be updated real-time when user changes the clusters state, but it doesn't work in this way except for first endpoint

**Comment by brdandu** [comment]
The PR was not merged for this

**Comment by brdandu** [comment]
The goal here is to now get rid of endpoint summary. We had long conversations on this and this is not really needed and not worth spending so much time on it. So get rid of cluster, attribute and command counts.

**Comment by paulr34** [comment]
@brdandu I just tested this and it is fixed. Please reopen if you disagree.
