### ISSUE TITLE
ZAP non-determinism on lighting-app in CHIP

### ISSUE THREAD

**Issue by andy31415** [project-chip/zap#766]
We recently started to see ZAP differences in output, like:

https://github.com/project-chip/connectedhomeip/actions/runs/3290277362/jobs/5422900622
https://github.com/project-chip/connectedhomeip/actions/runs/3291431383/jobs/5425574221
https://github.com/project-chip/connectedhomeip/actions/runs/3291544578/jobs/5425840763

We have not updated zap nor lighting app zap inputs in some time now, yet generating gives differences. This seems to be environment dependent - on my machine I seem to frequently (always so far) get it:

```
> git status
On branch master
Your branch is ahead of 'origin/master' by 64 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
> time podman exec -w /workspace bld_zap ./scripts/tools/zap_regen_all.py
# .... this takes a long time
________________________________________________________
Executed in  358.15 secs      fish           external
   usr time  139.76 millis    0.00 micros  139.76 millis
   sys time  106.54 millis  646.00 micros  105.89 millis
> git status
On branch master
Your branch is ahead of 'origin/master' by 64 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   zzz_generated/lighting-app/zap-generated/IMClusterCommandHandler.cpp
        modified:   zzz_generated/lighting-app/zap-generated/PluginApplicationCallbacks.h
        modified:   zzz_generated/lighting-app/zap-generated/access.h
        modified:   zzz_generated/lighting-app/zap-generated/callback-stub.cpp
        modified:   zzz_generated/lighting-app/zap-generated/endpoint_config.h
        modified:   zzz_generated/lighting-app/zap-generated/gen_config.h

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by brdandu** [comment]
Updating based on the slack conversation:
In the zap_regen_all.py I see both apps generating into the same output folder which is causing the Regen diff.
- ./scripts/tools/zap/generate.py examples/lighting-app/lighting-common/lighting-app.zap -o zzz_generated/lighting-app/zap-generated and 
- ./scripts/tools/zap/generate.py examples/lighting-app/nxp/zap/lighting-on-off.zap -o zzz_generated/lighting-app/zap-generated
For reference: https://csamembers.slack.com/archives/C01B01GH64E/p1666295523791349

**Comment by brdandu** [comment]
@andy31415 do you mind if I close this as not a zap issue?
