### ISSUE TITLE
When running a "build and release" job, it will execute even if JEST and Cypress tests are failing

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#798]
We need to put in place proper dependencies. We should NOT do a build-and-release until the unit tests are all passing.

I don't know how to get this done without collapsing multiple workflows into a single one, that has a "release" job doing a "needs:" clause on the previous jobs of testing.

**Comment by jingteng25742** [comment]
Closing as current release workflow has such behavior already.
