### ISSUE TITLE
Commands don't show up in the UI

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#800]
There seems to be a persistent bug where commands don't show up. For example, the Identify cluster should show this:

![image](https://user-images.githubusercontent.com/7923190/201345717-d7f1669e-9376-4d17-af07-68d4f3cd2b67.png)

But sometime these commands are not shown, and an empty tab is shown instead.
Example of a test file.
[zapfile.zip](https://github.com/project-chip/zap/files/9990421/zapfile.zip)

**Comment by brdandu** [comment]
Unable to reproduce on my end but we at least have a notification in the zap UI when a cluster has no commands. Please re-open this with more information if this stops working again.
