### ISSUE TITLE
there are errors in endpoint_config if added multiple eps

### ISSUE THREAD

**Issue by Leo2442926161** [project-chip/zap#833]
Dear all,  

there are errors in endpoint_config.h if I added ep0(root node), ep1(humidity sensor) and ep2(temperature sensor), is there anything should to be noticed? or is there ways to updated my zap application?

The brief error as below, I also attched the endpoint_config.h file, please kindly take a look, thank you.
```
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/zzz_generated/H1_EF4_Z22/zap-generated/endpoint_config.h:671:29: error: exponent has no digits
  671 | #define ATTRIBUTE_MAX_SIZE (337ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4211142)
      |                             ^~~~~~~~
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/src/app/util/attribute-storage.cpp:65:6: note: in expansion of macro 'ATTRIBUTE_MAX_SIZE'
   65 | #if (ATTRIBUTE_MAX_SIZE == 0)
      |      ^~~~~~~~~~~~~~~~~~
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/zzz_generated/H1_EF4_Z22/zap-generated/endpoint_config.h:671:37: error:  ':' without preceding '?'
  671 | #define ATTRIBUTE_MAX_SIZE (337ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4211142)
      |                                     ^
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/src/app/util/attribute-storage.cpp:65:6: note: in expansion of macro 'ATTRIBUTE_MAX_SIZE'
   65 | #if (ATTRIBUTE_MAX_SIZE == 0)
      |      ^~~~~~~~~~~~~~~~~~
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/zzz_generated/H1_EF4_Z22/zap-generated/endpoint_config.h:671:29: error: exponent has no digits
  671 | #define ATTRIBUTE_MAX_SIZE (337ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4211142)
      |                             ^~~~~~~~
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/src/app/util/attribute-storage.cpp:68:31: note: in expansion of macro 'ATTRIBUTE_MAX_SIZE'
   68 | #define ACTUAL_ATTRIBUTE_SIZE ATTRIBUTE_MAX_SIZE
      |                               ^~~~~~~~~~~~~~~~~~
../../../examples/H1_EF4_Z22/efr32/third_party/connectedhomeip/src/app/util/attribute-storage.cpp:71:23: note: in expansion of macro 'ACTUAL_ATTRIBUTE_SIZE'
   71 | uint8_t attributeData[ACTUAL_ATTRIBUTE_SIZE];
```

**Comment by brdandu** [comment]
Adding + @bzbarsky-apple and @tecimovic to the conversation. Any reason we still have not shifted to zap-config.h template for Matter?

**Comment by brdandu** [comment]
> @brdandu Does zap-config generate output that can be consumed by the Silicon Labs code that was contributed to Matter?
> 
> But for the above: what version of ZAP is being used? That looks like something that was not handling non-external list-typed attributes correctly, which has been fixed for a _long_ time.....

I do not know if zap-config has everything that endpoint_config has since there may have been a divergence that I do not know. @jmartinez-silabs , @jepenven-silabs it might be good to check the difference between the two an add whatever is needed to zap-config.

@bzbarsky-apple, @Leo2442926161  can I close this issue in that case?

**Comment by bzbarsky-apple** [comment]
Well, it would be good to understand the exact steps that were followed that led to the broken behavior...

**Comment by paulr34** [comment]
Closing since there was no follow up with exact steps. Please reopen if you would like to follow up.

**Comment by lopeznegrete** [comment]
Can we reopen this issue?

I've got the below build errors:

`                 from /home/lopeznegrete/ncs/modules/lib/matter/src/app/util/attribute-storage.cpp:18:
/home/lopeznegrete/Projects/Matter/tempsensor/src/zap-generated/endpoint_config.h:632:29: error: exponent has no digits
  632 | #define ATTRIBUTE_MAX_SIZE (125ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4222242)
      |                             ^~~~~~~~
/home/lopeznegrete/ncs/modules/lib/matter/src/app/util/attribute-storage.cpp:50:6: note: in expansion of macro 'ATTRIBUTE_MAX_SIZE'
   50 | #if (ATTRIBUTE_MAX_SIZE == 0)
      |      ^~~~~~~~~~~~~~~~~~
/home/lopeznegrete/Projects/Matter/tempsensor/src/zap-generated/endpoint_config.h:632:37: error:  ':' without preceding '?'
  632 | #define ATTRIBUTE_MAX_SIZE (125ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4222242)
      |                                     ^
/home/lopeznegrete/ncs/modules/lib/matter/src/app/util/attribute-storage.cpp:50:6: note: in expansion of macro 'ATTRIBUTE_MAX_SIZE'
   50 | #if (ATTRIBUTE_MAX_SIZE == 0)
      |      ^~~~~~~~~~~~~~~~~~
/home/lopeznegrete/Projects/Matter/tempsensor/src/zap-generated/endpoint_config.h:632:29: error: exponent has no digits
  632 | #define ATTRIBUTE_MAX_SIZE (125ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4222242)
      |                             ^~~~~~~~
/home/lopeznegrete/ncs/modules/lib/matter/src/app/util/attribute-storage.cpp:53:31: note: in expansion of macro 'ATTRIBUTE_MAX_SIZE'
   53 | #define ACTUAL_ATTRIBUTE_SIZE ATTRIBUTE_MAX_SIZE
      |                               ^~~~~~~~~~~~~~~~~~
/home/lopeznegrete/ncs/modules/lib/matter/src/app/util/attribute-storage.cpp:56:23: note: in expansion of macro 'ACTUAL_ATTRIBUTE_SIZE'
   56 | uint8_t attributeData[ACTUAL_ATTRIBUTE_SIZE];
      |                       ^~~~~~~~~~~~~~~~~~~~~
/home/lopeznegrete/Projects/Matter/tempsensor/src/zap-generated/endpoint_config.h:587:22: error: exponent has no digits
  587 |       .clusterSize = 0ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array42, \
      |                      ^~~~~~
/home/lopeznegrete/ncs/modules/lib/matter/src/app/util/attribute-storage.cpp:104:54: note: in expansion of macro 'GENERATED_CLUSTERS'
  104 | constexpr const EmberAfCluster generatedClusters[] = GENERATED_CLUSTERS;
      |                                                      ^~~~~~~~~~~~~~~~~~
/home/lopeznegrete/Projects/Matter/tempsensor/src/zap-generated/endpoint_config.h:617:31: error: exponent has no digits
  617 |   { ZAP_CLUSTER_INDEX(14), 3, 90ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4212 }, \`

I have completed the following steps:

1. Starting from the template sample under the NordicSemi ncs v2.4.0.
2. Remove zap-generated folder
3. Open src/template.zap file with zap tool.
4. Then. Select '+ ADD NEW ENDPOINT' > Select 'Matter Temperature Sensor (0x0302)' > Press Create
5. Then, generate files to src/zap-generated folder
6. Execute west build

This line is extracted from endpoint_config.h. From other zap-generated files, this define is a number (e.g (170)).

`#define ATTRIBUTE_MAX_SIZE (125ERROR: DeviceTypeList, invalid size, arrayERROR: ServerList, invalid size, arrayERROR: ClientList, invalid size, arrayERROR: PartsList, invalid size, array4222242)`

**Comment by lopeznegrete** [comment]
Solved the error by defining DeviceTypeList, ServerList, ClientList, and PartsList to 0 instead of leaving it blank

**Comment by bzbarsky-apple** [comment]
> Solved the error by defining DeviceTypeList, ServerList, ClientList, and PartsList to 0 instead of leaving it blank

Defining it to 0 where exactly, @lopeznegrete ?

**Comment by bzbarsky-apple** [comment]
That really should not matter for these attributes...  It sounds like something is very confused in the way you are generating these things, so the "these must be external" logic is not getting picked up.  Setting default to 0 might "fix" the compile issue, but I expect the generated configuration is still wrong.

**Comment by lopeznegrete** [comment]
@bzbarsky-apple 
I am using the zap tool out of the box and following the above steps. No changes whatsoever.  What could be confused in the way that files are generated? What "external" logic is not picked up?

Zap and system version
![image](https://github.com/project-chip/zap/assets/18558551/b3a51fc5-b025-409d-9a43-69e54a4dc68e)

**Comment by bzbarsky-apple** [comment]
1. Exactly what are the contents of "template sample under the NordicSemi ncs v2.4.0"?
2. Exactly how do you do the "generate files to src/zap-generated folder" step?

**Comment by lopeznegrete** [comment]
> 1. Exactly what are the contents of "template sample under the NordicSemi ncs v2.4.0"?

Template sample under Nordic NCS v2.4.0 branch

https://github.com/nrfconnect/sdk-nrf/tree/v2.4-branch/samples/matter/template

No much to add here.

> 2. Exactly how do you do the "generate files to src/zap-generated folder" step?

I click on the generate option in the zap tool and selected the src/zap-generated folder as target folder. Please see image below.

![image](https://github.com/project-chip/zap/assets/18558551/f6403b05-68c1-435b-bd9f-abbef24b25ce)

No much else to add here neither.

**Comment by bzbarsky-apple** [comment]
> I click on the generate option in the zap tool 

@lopeznegrete There is your problem.  That's almost certainly not passing the right config to the generation to take into account SDK settings.  You want to use the Matter generation scripts...

**Comment by lopeznegrete** [comment]
> > I click on the generate option in the zap tool
> 
> @lopeznegrete There is your problem. That's almost certainly not passing the right config to the generation to take into account SDK settings. You want to use the Matter generation scripts...

How do you do that?

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/docs/code_generation.md#running-codegen

**Comment by lopeznegrete** [comment]
> > I click on the generate option in the zap tool
> 
> @lopeznegrete There is your problem. That's almost certainly not passing the right config to the generation to take into account SDK settings. You want to use the Matter generation scripts...

I don't find it appropriate to quote it as 'your problem'. From a user perspective, if there is a button that states "Generate ..." take for granted that most people will understand this button is to generate the files. Regardless if it is a Matter generation. To be constructive, that button or info around should indicate under what circumstances it will generate valid files.

**Comment by bzbarsky-apple** [comment]
Just to be clear: 

1. "your problem" here just meant "the problem you are running into".
2. I completely agree that the fact that "Generate..." is (a) enabled and (b) does the wrong thing is wrong.

That said, filing a new clear issue about that problem, rather than using this one (which was initially about something else and has a bunch of noise) is probably the best approach here.
