### ISSUE TITLE
Multiple device type in a single endpoint

### ISSUE THREAD

**Issue by LucaValbusa19** [project-chip/zap#862]
I am developing a Matter device with OTA Update functionalities. I need to add both Root Node and OTA Requestor device types in endpoint 0. Why am i not able to do it (even in endpoint 1)?

**Comment by cecille** [comment]
Would you be able to share a bit more about what you're trying to do here? I wasn't sure what you were trying to do with EP1.

What does the desired endpoint composition look like? Are you running this through the zap GUI? Do you have a zap file generated that you could share?

Per the spec (section 9.2)
```
A root node device type SHALL be a singleton on the root node endpoint.
The PartsList of the Descriptor cluster on the root node endpoint SHALL list all endpoints on the node, except the root node endpoint.
The root node endpoint SHALL NOT exist in any other endpoint’s PartsList on the node.
The root node endpoint requirements are defined by a node scoped device type.
There SHALL be only one root node endpoint for the node.
```

So you can't put any other device type on the root node endpoint (ep0) and the root node can't appear on any other endpoint.

**Comment by LucaValbusa19** [comment]
I have this composition:
EP0 - Root Node
EP1 - On/Off Plug-in Unit

I am now trying to implement the OTA Software Update Requestor (Server) and OTA Software Update Provider (Client) clusters. 
I am using a Nordic Semiconductor SoC and i saw that in their samples those clusters were included in the EP0. 

Since in the Root Node device type specification they are not even optionals, i tought that Nordic included them developing a composed device type in EP0 (Root Node + OTA Requestor).

How do you suggest to include OTA Requestor device type?

**Comment by cecille** [comment]
I think most production devices just use a separate endpoint, but it might be worth confirming with folks on the slack if you're on there.

**Comment by LucaValbusa19** [comment]
I forwarded the question to the Nordic Semiconductor reference for Matter Data Model and it comes out that the endpoint 0 can be composed by Root Node + OTA Requestor device types since in the Device Library specification, for the Root Node is stated:
![RootNodeSpec](https://user-images.githubusercontent.com/120710980/208848135-6aeaf7fd-e1cf-4e6a-96e9-1356c0a71fad.PNG)
This is the best solution for my device, but how can i implement it with ZAP tool?

**Comment by JasonHu1** [comment]
Now the path of endpoint_config.h is the out/gen/zapgen/ directory. 
This requires that the file content cannot be manually modified, and can only be generated by Zap. 
When endpoint 1 requires two device types (eg ota provider and aggregator) at the same time, how to use zap to write ota provider and aggregator as the default values to the endpoint_config.h ?

**Comment by bzbarsky-apple** [comment]
>  This requires that the file content cannot be manually modified, and can only be generated by Zap.

That's not quite true.  You can pre-generate and then modify.  But it's extremely painful, yes.
