### ISSUE TITLE
Custom cluster with manufacturer code can lead to bad cluster ids in endpoint_config.h

### ISSUE THREAD

**Issue by wijnandatgoogle** [project-chip/zap#885]
My original comment shows where the problem I ran into can happen:
https://github.com/project-chip/zap/commit/a2d0216b453d58855da154114ae549da1bd36690#r95598454

My working assumption was that the cluster code must include a manufacturer code, and a lower 16 bit in the range starting from 0xFC00 to be considered valid.
Adding the manufacturer code in the cluster tag, and also adding it in the cluster code leads to a double adding on the upper 16 bit.

Removing the manufacturer code from the cluster code in XML causes the cluster to not be recognized, and references to it are removed in my codebase. 

As suggested in the comments, if the upper 16 bits are ORred together, it would work. Perhaps an assert for equality would be nice, when both upper 16 bits in code and the manufacturer code are non-zero.

**Comment by bzbarsky-apple** [comment]
> Removing the manufacturer code from the cluster code in XML causes the cluster to not be recognized, and references to it are removed in my codebase.

That's pretty strange, since I believe we have examples of this in the code that do work...

**Comment by wijnandatgoogle** [comment]
After looking more, I found some other files that have the same problems, and some that don't (all with the same XML):

Bad:
$MY_SERVER_ZAP_DIR/zap-generated/endpoint_config.h
$MY_CHIP_ROOT/src/darwin/Framework/CHIP/zap-generated/MTRClusterConstants.h
$MY_CHIP_ROOT/zzz_generated/app-common/app-common/zap-generated/ids/Clusters.h

Good:
$MY_CHIP_ROOT/zzz_generated/darwin-framework-tool/zap-generated/cluster/Commands.h
$MY_CHIP_ROOT/zzz_generated/app-common/app-common/zap-generated/cluster-id.h
$MY_CHIP_ROOT/zzz_generated/chip-tool/zap-generated/cluster/Commands.h

**Comment by bzbarsky-apple** [comment]
@wijnandatgoogle If you look at src/app/zap-templates/zcl/data-model/chip/fault-injection-cluster.xml, that is a cluster that uses a "code" in the manufacturer-specific range without using manufacturerCode at all.

**Comment by bzbarsky-apple** [comment]
If you try to use manufacturerCode + 16-bit-code, then it looks like it should mostly work, except for the code-generated access.h, which ends up using the wrong cluster id.

**Comment by bzbarsky-apple** [comment]
Though actually, no, it ends up with garbage in various places.  I'll try to fix it, but that codepath is really not tested well.  The tested thing is to not set manufacturerCode at all and just have a 32-bit code with the right high bits set.

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/zap/pull/888
