### ISSUE TITLE
zapSessionId is undefined under Jest test

### ISSUE THREAD

**Issue by aspecter** [project-chip/zap#892]
Running [**server-bare.test.js's test initial state**](https://github.com/project-chip/zap/blob/master/test/server-bare.test.js#L265) test failing with Quasar 2 because [**_httpGetInitialState_**](https://github.com/project-chip/zap/blob/master/src-electron/rest/user-data.js#L330) function's [**_zapSessionId_**](https://github.com/project-chip/zap/blob/master/src-electron/rest/user-data.js#L332) is not exists in the **user-data.js** file.
With Quasar 1 the **_zapSessionId_** is also undefined, just the test doesn't fail for some reason - probably for some Jest configuration, although it should. In this case, the httpGetInitialState just returns an object with 3 empty array `{ endpointTypes: [], endpoints: [], sessionKeyValues: [] }` and that is why the test does not fail, because these empty arrays' value are truthy.

**Comment by jingteng25742** [comment]
@aspecter Can you point me to the failing tests in question?
[server-bare.test.js's test initial state](https://github.com/project-chip/zap/blob/master/test/server-bare.test.js#L265), it is checking that the returned data have those specific keys defined within the REST api result. It doesn't check the array values.

**Comment by aspecter** [comment]
@jingteng25742 Those arrays are empty, and the logic somehow just goes through with the undefined value.
I have the failing test issue with the Quasar 2 and with the newer Jest, where because of the undefined value - zapSessionId - the test fails. This is why [I've put a skip on the failing test](https://github.com/project-chip/zap/pull/865/commits/5ab9260c7f93b4510b6ef2431cf96d34b962cc52#diff-396358ac324e4e2a2d343595c739e49b8ffa82b492ae7934f0da4b20eedcac29).
