### ISSUE TITLE
Pre-built zap Arm Linux binaries

### ISSUE THREAD

**Issue by sandeepmistry** [project-chip/zap#897]
It would be great if this project could provide pre-built binaries of `zap` in the [releases](https://github.com/project-chip/zap/releases) for 64-bit Arm Linux.

**Comment by ksperling-apple** [comment]
Maybe we could also look at generating separate release packages for just the cli?

**Comment by jingteng25742** [comment]
@sandeepmistry 
The arm64 release change will be merged in the upcoming week

@ksperling-apple 
Currently, the UI / CLI is packaged in one to offer customers the option of switching in-between if needed.

**Comment by jingteng25742** [comment]
Closing
