### ISSUE TITLE
Question of ZAP file generate

### ISSUE THREAD

**Issue by joonhaengHeo** [project-chip/zap#930]
When creating a file using ZAP, is there a way to distinguish Global elements as shown in the spec below?

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/6cf896275a4361f2204dc997e5e213c8e86c25f0/src/data_model/Data-Model.adoc#global-elements

**Comment by paulr34** [comment]
the link has a 404 error code so I am closing this

**Comment by brdandu** [comment]
> the link has a 404 error code so I am closing this

Wondering if we dp not have access to the page
