### ISSUE TITLE
helper-endpointconfig.js is impossible to make backwards-compatible in its current state

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#940]
`src-electron/generator/helper-endpointconfig.js` has code like this:

```
function endpoint_reporting_config_defaults(options) {
...
    ret += `  { ZAP_REPORT_DIRECTION(${r.direction}), ${r.endpoint}, ${r.clusterId}, ${r.attributeId}, ${mask}, ${r.mfgCode}, {{ ${r.minOrSource}, ${r.maxOrEndpoint}, ${r.reportableChangeOrTimeout} }} }, /* ${r.name} */ \\\n`
```

which assumes that it's initializing particular C/C++ structs with a specific set of members that come in a particular order.  Or another example, which recently in fact changed order of struct members:

```
function endpoint_attribute_list(options) {
...
    ret += `  { ${finalDefaultValue}, ${at.id}, ${at.size}, ${at.type}, ${mask} }, /* ${at.name} */  \\\n`
```

This means that the JS has to change in sync with the relevant C++ struct definitions.

We need to either need to have these helpers be able to produce different output based on `options` or change the structure here so that the iteration over the list happens in the template, or something.

**Comment by tecimovic** [comment]
@bzbarsky-apple : does your environment use C99-like initializer designators. As in: 
   { .a = 1, .b = 2, .c = 3 }
instead of classic:
  {1, 2, 3}

?

**Comment by tecimovic** [comment]
Even with designators, we would still have to pass in the actual struct field names then, so I wonder if it makes sense anyway. 

So we would have to do some way to pass as an option either the names of the fields, or the order of the fields anyway.....

**Comment by bzbarsky-apple** [comment]
> does your environment use C99-like initializer designator

It's possible that we could.  It's not supported until C++20, but maybe it's supported in gnu++14 and hence OK-ish to use....

But that only helps with reordering, not with adding/removing fields.

**Comment by tecimovic** [comment]
Ok....

I'll add a hash option, so you will be able to do something like:
   `{{endpoint_reporting_config_defaults order="direction,endpoint,clusterId,attributeId,mask,mfgCode,minmax"}}`
 
So if you add/remove fields and change order, you just maintain this ordering in the template, and not disturb old templates.

Default value will be set to the oldest still required supported case.
