### ISSUE TITLE
could not display zap-cli  

### ISSUE THREAD

**Issue by cheng5230** [project-chip/zap#962]
**Ubuntu systeminfo**
Linux version 5.15.0-60-generic (buildd@lcy02-amd64-017) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023

double click no show
 
![微信截图_20230302170151](https://user-images.githubusercontent.com/38391461/222381539-958be01d-b1b3-4c00-9537-9d48693fd83f.png)

![无标题](https://user-images.githubusercontent.com/38391461/222382157-0073f1bd-8a6a-491b-a715-0cc0ac206991.png)

**Comment by jingteng25742** [comment]
hi @cheng5230 , as the name implies, "zap-cli" is a purely command line tool with no UI interface. 
If UI is expected, "zap" should be invoked instead.
