### ISSUE TITLE
zap-cli: "Could not retrieve version from .version.json"

### ISSUE THREAD

**Issue by vindicatorr** [project-chip/zap#977]
Commit: c0a2dfc986db47cbfba9d470df59c1b0d0925874

Anything run from zap-cli always results in that json output: `{"level":50,"time":1679635807340,"pid":1859675,"hostname":"<hostName>","name":"zap","msg":"Could not retrieve version from .version.json"}`

This is just one of the things that prevents `connectedhomeip/examples/all-clusters-minimal-app/nrfconnect` from building:
```
...
NRF_802154_CARRIER_FUNCTIONS_ENABLED=0
[8/828] Generating gen/app-zapgen/zapgen/app-templates/z.../app-templates/zap-generated/IMClusterCommandHandler.cpp
FAILED: gen/app-zapgen/zapgen/app-templates/zap-generated/access.h ...

<pathTo>/connectedhomeip/examples/all-clusters-minimal-app/nrfconnect/out/build/nrf52840dongle_nrf52840/gen/app-zapgen/zapgen/app-templates/zap-generated/IMClusterCommandHandler.cpp
...
<pathTo>/connectedhomeip/scripts/tools/zap/generate.py ...
...
Searching for zcl file from <pathTo>/connectedhomeip/examples/all-clusters-minimal-app/nrfconnect/../all-clusters-common/all-clusters-minimal-app.zap
Failed to find `Version: ....` line from ['<pathTo>/zap-cli'] --version
[13/828] Building CXX object modules/openthread/build/src/cli/CMakeFiles/openthread-cli-ftd.dir/cli.cpp.obj
ninja: build stopped: subcommand failed.
```

**Comment by paulr34** [comment]
here is my output , what versions are you using?

**paregan@mac0015027 zap-mac % ./zap-cli --version
Version: 2023.3.27
Feature level: 94
Hash: 15f96c4f997301da1174ef29156c1c7d442f5d44
Date: 2023-03-27T17:20:50.000Z
Mode: binary
Executable: ./zap-cli**

**Comment by vindicatorr** [comment]
Master commit c0a2dfc986db47cbfba9d470df59c1b0d0925874
```
$ ./zap-cli --version
{"level":50,"time":1680023424069,"pid":2468062,"hostname":"computerName","name":"zap","msg":"Could not retrieve version from .version.json"}
Version: 
Feature level: 94
Hash: 0
Date: 
Mode: binary
Executable: ./zap-cli
```

**Comment by vindicatorr** [comment]
Same result with master commit 15f96c4f997301da1174ef29156c1c7d442f5d44.

**Comment by paulr34** [comment]
https://github.com/project-chip/zap/actions/runs/4534769426 1.) download this zip for whatever OS you're using
 2.) unzip
 3.) cd into the folder
 4.) execute ./zap-cli --version

I just did it and it worked.

**Comment by vindicatorr** [comment]
I get that, but it's just that I should be able to do it myself. It's what I do with everything that I can.
Not to mention, I'd need to d/l 150+MB everytime I'd be upgrading this vs just fetching small commits and only updating shared node packages (eg packages that may be used for other projects as well).

Currently d/ling your pre-built, and will report back...
