### ISSUE TITLE
Add support for S (Scene) Quality

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/zap#980]
Linked with this [matter issue](https://github.com/project-chip/connectedhomeip/issues/24177), moving it from this [previously opened issue](https://github.com/project-chip/zap/issues/174).

We need a way to specify to Zap if a cluster is "Sceneable" (supports the "S" quality).

**Comment by brdandu** [comment]
Associated CHIP Repo PR: https://github.com/project-chip/connectedhomeip/pull/34516
